/***************************************************************************
 Headers
***************************************************************************/

//#include <mpatrol.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <math.h>
#include <error.h>
#include <dos.h>
#include <exec/memory.h>
#include <exec/execbase.h>
#include <dos/datetime.h>
#include <dos/dostags.h>
#include <dos/doshunks.h>
#include <workbench/workbench.h>
#include <workbench/startup.h>
#include <devices/printer.h>
#include <intuition/icclass.h>
#include <intuition/gadgetclass.h>
#include <datatypes/pictureclass.h>
#include <datatypes/soundclass.h>
#include <libraries/locale.h>
#include <libraries/asl.h>
#include <libraries/mui.h>
#include <libraries/gadtools.h>
#include <libraries/openurl.h>
#include <libraries/genesis.h>
#include <libraries/cmanager.h>
#include <mui/listtree_mcc.h>
#include <mui/nlist_mcc.h>
#include <mui/nlistview_mcc.h>
#include <mui/texteditor_mcc.h>
#include <mui/betterstring_mcc.h>
#include <mui/toolbar_mcc.h>
#include <rexx/rxslib.h>
#include <rexx/storage.h>
#include <xpk/xpk.h>
#include <clib/muimaster_protos.h>
#include <clib/alib_protos.h>
#include <clib/dos_protos.h>
#include <clib/exec_protos.h>
#include <clib/utility_protos.h>
#include <clib/locale_protos.h>
#include <clib/icon_protos.h>
#include <clib/graphics_protos.h>
#include <clib/datatypes_protos.h>
#include <clib/wb_protos.h>
#include <clib/macros.h>
#include <clib/wb_protos.h>
#include <clib/iffparse_protos.h>
#include <clib/keymap_protos.h>
#include <clib/rexxsyslib_protos.h>
#include <clib/xpkmaster_protos.h>
#include <clib/openurl_protos.h>
#include <clib/miami_protos.h>
#include <clib/genesis_protos.h>
#include <clib/cmanager_protos.h>
#include <pragmas/muimaster_pragmas.h>
#include <pragmas/openurl_pragmas.h>
#include <pragmas/xpkmaster_pragmas.h>
#include <pragmas/miami_pragmas.h>
#include <pragmas/genesis_pragmas.h>
#include <pragmas/cmanager_pragmas.h>
#include <NewReadArgs.h>
