/* FILE GENERATED BY gen_gates.pl - DO NOT EDIT */
#include <exec/types.h>
#include <emul/emulinterface.h>
#include <emul/emulregs.h>
typedef void *Msg;
typedef struct { long dummy; } Object;
void AY_SendMailFunc(void);
static void  Trampoline_AY_SendMailFunc(void)
{
   AY_SendMailFunc();
}
const struct EmulLibEntry Gate_AY_SendMailFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AY_SendMailFunc };

void AY_GoPageFunc(void);
static void  Trampoline_AY_GoPageFunc(void)
{
   AY_GoPageFunc();
}
const struct EmulLibEntry Gate_AY_GoPageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AY_GoPageFunc };

void DoublestartFunc(void);
static void  Trampoline_DoublestartFunc(void)
{
   DoublestartFunc();
}
const struct EmulLibEntry Gate_DoublestartFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DoublestartFunc };

void AB_FromAddrBook(ULONG *arg);
static void  Trampoline_AB_FromAddrBook(void)
{
   AB_FromAddrBook((ULONG *)REG_A1);
}
const struct EmulLibEntry Gate_AB_FromAddrBook = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_FromAddrBook };

void AB_DoubleClick(void);
static void  Trampoline_AB_DoubleClick(void)
{
   AB_DoubleClick();
}
const struct EmulLibEntry Gate_AB_DoubleClick = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_DoubleClick };

void AB_Sort(int *arg);
static void  Trampoline_AB_Sort(void)
{
   AB_Sort((int *)REG_A1);
}
const struct EmulLibEntry Gate_AB_Sort = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_Sort };

void AB_NewABookFunc(void);
static void  Trampoline_AB_NewABookFunc(void)
{
   AB_NewABookFunc();
}
const struct EmulLibEntry Gate_AB_NewABookFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_NewABookFunc };

void AB_OpenABookFunc(void);
static void  Trampoline_AB_OpenABookFunc(void)
{
   AB_OpenABookFunc();
}
const struct EmulLibEntry Gate_AB_OpenABookFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_OpenABookFunc };

void AB_AppendABookFunc(void);
static void  Trampoline_AB_AppendABookFunc(void)
{
   AB_AppendABookFunc();
}
const struct EmulLibEntry Gate_AB_AppendABookFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_AppendABookFunc };

void AB_SaveABookFunc(void);
static void  Trampoline_AB_SaveABookFunc(void)
{
   AB_SaveABookFunc();
}
const struct EmulLibEntry Gate_AB_SaveABookFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_SaveABookFunc };

void AB_SaveABookAsFunc(void);
static void  Trampoline_AB_SaveABookAsFunc(void)
{
   AB_SaveABookAsFunc();
}
const struct EmulLibEntry Gate_AB_SaveABookAsFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_SaveABookAsFunc };

void AB_PrintABookFunc(void);
static void  Trampoline_AB_PrintABookFunc(void)
{
   AB_PrintABookFunc();
}
const struct EmulLibEntry Gate_AB_PrintABookFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_PrintABookFunc };

void AB_PrintFunc(void);
static void  Trampoline_AB_PrintFunc(void)
{
   AB_PrintFunc();
}
const struct EmulLibEntry Gate_AB_PrintFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_PrintFunc };

void AB_AddEntryFunc(int *arg);
static void  Trampoline_AB_AddEntryFunc(void)
{
   AB_AddEntryFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_AB_AddEntryFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_AddEntryFunc };

void AB_EditFunc(void);
static void  Trampoline_AB_EditFunc(void)
{
   AB_EditFunc();
}
const struct EmulLibEntry Gate_AB_EditFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_EditFunc };

void AB_DeleteFunc(void);
static void  Trampoline_AB_DeleteFunc(void)
{
   AB_DeleteFunc();
}
const struct EmulLibEntry Gate_AB_DeleteFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_DeleteFunc };

void AB_DuplicateFunc(void);
static void  Trampoline_AB_DuplicateFunc(void)
{
   AB_DuplicateFunc();
}
const struct EmulLibEntry Gate_AB_DuplicateFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_DuplicateFunc };

void AB_FindFunc(void);
static void  Trampoline_AB_FindFunc(void)
{
   AB_FindFunc();
}
const struct EmulLibEntry Gate_AB_FindFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_FindFunc };

void AB_OpenFunc(int *arg);
static void  Trampoline_AB_OpenFunc(void)
{
   AB_OpenFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_AB_OpenFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_OpenFunc };

void AB_Close(void);
static void  Trampoline_AB_Close(void)
{
   AB_Close();
}
const struct EmulLibEntry Gate_AB_Close = { TRAP_LIBNR, 0, (void(*)())Trampoline_AB_Close };

struct MUIP_NListtree_ConstructMessage;
struct ABEntry * AB_LV_ConFunc( struct MUIP_NListtree_ConstructMessage *msg);
static struct ABEntry *  Trampoline_AB_LV_ConFunc(void)
{
   return AB_LV_ConFunc((struct MUIP_NListtree_ConstructMessage *)REG_A1);
}
const struct EmulLibEntry Gate_AB_LV_ConFunc = { TRAP_LIB, 0, (void(*)())Trampoline_AB_LV_ConFunc };

struct MUIP_NListtree_DestructMessage;
long AB_LV_DesFunc( struct MUIP_NListtree_DestructMessage *msg);
static long  Trampoline_AB_LV_DesFunc(void)
{
   return AB_LV_DesFunc((struct MUIP_NListtree_DestructMessage *)REG_A1);
}
const struct EmulLibEntry Gate_AB_LV_DesFunc = { TRAP_LIB, 0, (void(*)())Trampoline_AB_LV_DesFunc };

struct Hook;
struct MUIP_NListtree_DisplayMessage;
long AB_LV_DspFunc( struct Hook *hook,  struct MUIP_NListtree_DisplayMessage *msg);
static long  Trampoline_AB_LV_DspFunc(void)
{
   return AB_LV_DspFunc((struct Hook *)REG_A0, (struct MUIP_NListtree_DisplayMessage *)REG_A1);
}
const struct EmulLibEntry Gate_AB_LV_DspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_AB_LV_DspFunc };

struct IClass;
ULONG BC_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_BC_Dispatcher(void)
{
   return BC_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_BC_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_BC_Dispatcher };

struct IClass;
ULONG WS_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_WS_Dispatcher(void)
{
   return WS_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_WS_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_WS_Dispatcher };

struct IClass;
ULONG WL_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_WL_Dispatcher(void)
{
   return WL_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_WL_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_WL_Dispatcher };

struct IClass;
ULONG FL_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_FL_Dispatcher(void)
{
   return FL_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_FL_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_FL_Dispatcher };

struct IClass;
ULONG EL_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_EL_Dispatcher(void)
{
   return EL_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_EL_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_EL_Dispatcher };

struct IClass;
ULONG AL_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_AL_Dispatcher(void)
{
   return AL_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_AL_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_AL_Dispatcher };

struct IClass;
ULONG MW_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_MW_Dispatcher(void)
{
   return MW_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_MW_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_MW_Dispatcher };

struct IClass;
struct MUIP_TextEditor_HandleError;
ULONG TE_Dispatcher(struct IClass *cl, Object *obj, struct MUIP_TextEditor_HandleError *msg);
static ULONG  Trampoline_TE_Dispatcher(void)
{
   return TE_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (struct MUIP_TextEditor_HandleError *)REG_A1);
}
const struct EmulLibEntry Gate_TE_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_TE_Dispatcher };

struct IClass;
ULONG PL_Dispatcher(struct IClass *cl, Object *obj, Msg msg);
static ULONG  Trampoline_PL_Dispatcher(void)
{
   return PL_Dispatcher((struct IClass *)REG_A0, (Object *)REG_A2, (Msg)REG_A1);
}
const struct EmulLibEntry Gate_PL_Dispatcher = { TRAP_LIB, 0, (void(*)())Trampoline_PL_Dispatcher };

void CO_AddRule(void);
static void  Trampoline_CO_AddRule(void)
{
   CO_AddRule();
}
const struct EmulLibEntry Gate_CO_AddRule = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_AddRule };

void CO_DelRule(void);
static void  Trampoline_CO_DelRule(void)
{
   CO_DelRule();
}
const struct EmulLibEntry Gate_CO_DelRule = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_DelRule };

void CO_GetRUEntry(void);
static void  Trampoline_CO_GetRUEntry(void)
{
   CO_GetRUEntry();
}
const struct EmulLibEntry Gate_CO_GetRUEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_GetRUEntry };

void CO_PutRUEntry(void);
static void  Trampoline_CO_PutRUEntry(void)
{
   CO_PutRUEntry();
}
const struct EmulLibEntry Gate_CO_PutRUEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_PutRUEntry };

void CO_RemoteToggleFunc(int *arg);
static void  Trampoline_CO_RemoteToggleFunc(void)
{
   CO_RemoteToggleFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_CO_RemoteToggleFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_RemoteToggleFunc };

void CO_AddPOP3(void);
static void  Trampoline_CO_AddPOP3(void)
{
   CO_AddPOP3();
}
const struct EmulLibEntry Gate_CO_AddPOP3 = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_AddPOP3 };

void CO_DelPOP3(void);
static void  Trampoline_CO_DelPOP3(void)
{
   CO_DelPOP3();
}
const struct EmulLibEntry Gate_CO_DelPOP3 = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_DelPOP3 };

void CO_GetP3Entry(void);
static void  Trampoline_CO_GetP3Entry(void)
{
   CO_GetP3Entry();
}
const struct EmulLibEntry Gate_CO_GetP3Entry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_GetP3Entry };

void CO_PutP3Entry(void);
static void  Trampoline_CO_PutP3Entry(void)
{
   CO_PutP3Entry();
}
const struct EmulLibEntry Gate_CO_PutP3Entry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_PutP3Entry };

void CO_GetDefaultPOPFunc(void);
static void  Trampoline_CO_GetDefaultPOPFunc(void)
{
   CO_GetDefaultPOPFunc();
}
const struct EmulLibEntry Gate_CO_GetDefaultPOPFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_GetDefaultPOPFunc };

void CO_AddMimeView(void);
static void  Trampoline_CO_AddMimeView(void)
{
   CO_AddMimeView();
}
const struct EmulLibEntry Gate_CO_AddMimeView = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_AddMimeView };

void CO_DelMimeView(void);
static void  Trampoline_CO_DelMimeView(void)
{
   CO_DelMimeView();
}
const struct EmulLibEntry Gate_CO_DelMimeView = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_DelMimeView };

void CO_GetMVEntry(void);
static void  Trampoline_CO_GetMVEntry(void)
{
   CO_GetMVEntry();
}
const struct EmulLibEntry Gate_CO_GetMVEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_GetMVEntry };

void CO_PutMVEntry(void);
static void  Trampoline_CO_PutMVEntry(void)
{
   CO_PutMVEntry();
}
const struct EmulLibEntry Gate_CO_PutMVEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_PutMVEntry };

void CO_GetRXEntry(void);
static void  Trampoline_CO_GetRXEntry(void)
{
   CO_GetRXEntry();
}
const struct EmulLibEntry Gate_CO_GetRXEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_GetRXEntry };

void CO_PutRXEntry(void);
static void  Trampoline_CO_PutRXEntry(void)
{
   CO_PutRXEntry();
}
const struct EmulLibEntry Gate_CO_PutRXEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_PutRXEntry };

void CO_ImportCTypesFunc(void);
static void  Trampoline_CO_ImportCTypesFunc(void)
{
   CO_ImportCTypesFunc();
}
const struct EmulLibEntry Gate_CO_ImportCTypesFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_ImportCTypesFunc };

void CO_EditSignatFunc(int *arg);
static void  Trampoline_CO_EditSignatFunc(void)
{
   CO_EditSignatFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_CO_EditSignatFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_EditSignatFunc };

void CO_OpenConfig(void);
static void  Trampoline_CO_OpenConfig(void)
{
   CO_OpenConfig();
}
const struct EmulLibEntry Gate_CO_OpenConfig = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_OpenConfig };

void CO_SaveConfigAs(void);
static void  Trampoline_CO_SaveConfigAs(void)
{
   CO_SaveConfigAs();
}
const struct EmulLibEntry Gate_CO_SaveConfigAs = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_SaveConfigAs };

void CO_Restore(void);
static void  Trampoline_CO_Restore(void)
{
   CO_Restore();
}
const struct EmulLibEntry Gate_CO_Restore = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_Restore };

void CO_LastSaved(void);
static void  Trampoline_CO_LastSaved(void)
{
   CO_LastSaved();
}
const struct EmulLibEntry Gate_CO_LastSaved = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_LastSaved };

void CO_ResetToDefaultFunc(int *arg);
static void  Trampoline_CO_ResetToDefaultFunc(void)
{
   CO_ResetToDefaultFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_CO_ResetToDefaultFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_ResetToDefaultFunc };

void CO_ChangePageFunc(int *arg);
static void  Trampoline_CO_ChangePageFunc(void)
{
   CO_ChangePageFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_CO_ChangePageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_ChangePageFunc };

void CO_CloseFunc(int *arg);
static void  Trampoline_CO_CloseFunc(void)
{
   CO_CloseFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_CO_CloseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_CloseFunc };

void CO_OpenFunc(void);
static void  Trampoline_CO_OpenFunc(void)
{
   CO_OpenFunc();
}
const struct EmulLibEntry Gate_CO_OpenFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_OpenFunc };

struct Hook;
struct PageList;
long CO_PL_DspFunc(struct Hook *hook, char **array, struct PageList *entry);
static long  Trampoline_CO_PL_DspFunc(void)
{
   return CO_PL_DspFunc((struct Hook *)REG_A0, (char **)REG_A2, (struct PageList *)REG_A1);
}
const struct EmulLibEntry Gate_CO_PL_DspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_CO_PL_DspFunc };

void PO_List2TextFunc(Object *list, Object *text);
static void  Trampoline_PO_List2TextFunc(void)
{
   PO_List2TextFunc((Object *)REG_A2, (Object *)REG_A1);
}
const struct EmulLibEntry Gate_PO_List2TextFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_PO_List2TextFunc };

struct Hook;
struct TranslationTable;
long CO_LV_TDspFunc(struct Hook *hook, char **array, struct TranslationTable *entry);
static long  Trampoline_CO_LV_TDspFunc(void)
{
   return CO_LV_TDspFunc((struct Hook *)REG_A0, (char **)REG_A2, (struct TranslationTable *)REG_A1);
}
const struct EmulLibEntry Gate_CO_LV_TDspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_CO_LV_TDspFunc };

struct TranslationTable;
struct TranslationTable * CO_LV_TConFunc(struct TranslationTable *tt);
static struct TranslationTable *  Trampoline_CO_LV_TConFunc(void)
{
   return CO_LV_TConFunc((struct TranslationTable *)REG_A1);
}
const struct EmulLibEntry Gate_CO_LV_TConFunc = { TRAP_LIB, 0, (void(*)())Trampoline_CO_LV_TConFunc };

struct Hook;
long CO_LV_RxDspFunc(struct Hook *hook, char **array, int num);
static long  Trampoline_CO_LV_RxDspFunc(void)
{
   return CO_LV_RxDspFunc((struct Hook *)REG_A0, (char **)REG_A2, (int)REG_A1);
}
const struct EmulLibEntry Gate_CO_LV_RxDspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_CO_LV_RxDspFunc };

void PO_HandleXPKFunc(APTR text, APTR pop);
static void  Trampoline_PO_HandleXPKFunc(void)
{
   PO_HandleXPKFunc((APTR)REG_A1, (APTR)REG_A2);
}
const struct EmulLibEntry Gate_PO_HandleXPKFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_PO_HandleXPKFunc };

void PO_HandleTrans(APTR string, APTR pop);
static void  Trampoline_PO_HandleTrans(void)
{
   PO_HandleTrans((APTR)REG_A1, (APTR)REG_A2);
}
const struct EmulLibEntry Gate_PO_HandleTrans = { TRAP_LIBNR, 0, (void(*)())Trampoline_PO_HandleTrans };

void PO_HandleVar(APTR string, APTR pop);
static void  Trampoline_PO_HandleVar(void)
{
   PO_HandleVar((APTR)REG_A1, (APTR)REG_A2);
}
const struct EmulLibEntry Gate_PO_HandleVar = { TRAP_LIBNR, 0, (void(*)())Trampoline_PO_HandleVar };

void CO_PlaySoundFunc(int *arg);
static void  Trampoline_CO_PlaySoundFunc(void)
{
   CO_PlaySoundFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_CO_PlaySoundFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_CO_PlaySoundFunc };

void DI_CloseFunc(void);
static void  Trampoline_DI_CloseFunc(void)
{
   DI_CloseFunc();
}
const struct EmulLibEntry Gate_DI_CloseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DI_CloseFunc };

void DI_PasteFunc(void);
static void  Trampoline_DI_PasteFunc(void)
{
   DI_PasteFunc();
}
const struct EmulLibEntry Gate_DI_PasteFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DI_PasteFunc };

void DI_DeleteFunc(void);
static void  Trampoline_DI_DeleteFunc(void)
{
   DI_DeleteFunc();
}
const struct EmulLibEntry Gate_DI_DeleteFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DI_DeleteFunc };

void DI_DisplayFunc(void);
static void  Trampoline_DI_DisplayFunc(void)
{
   DI_DisplayFunc();
}
const struct EmulLibEntry Gate_DI_DisplayFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DI_DisplayFunc };

void DI_ModifyFunc(int *arg);
static void  Trampoline_DI_ModifyFunc(void)
{
   DI_ModifyFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_DI_ModifyFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DI_ModifyFunc };

void DI_OpenFunc(int *arg);
static void  Trampoline_DI_OpenFunc(void)
{
   DI_OpenFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_DI_OpenFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DI_OpenFunc };

struct Dict;
struct Dict * DI_LV_ConFunc(struct Dict *dict);
static struct Dict *  Trampoline_DI_LV_ConFunc(void)
{
   return DI_LV_ConFunc((struct Dict *)REG_A1);
}
const struct EmulLibEntry Gate_DI_LV_ConFunc = { TRAP_LIB, 0, (void(*)())Trampoline_DI_LV_ConFunc };

struct Dict;
long DI_LV_DesFunc(struct Dict *entry);
static long  Trampoline_DI_LV_DesFunc(void)
{
   return DI_LV_DesFunc((struct Dict *)REG_A1);
}
const struct EmulLibEntry Gate_DI_LV_DesFunc = { TRAP_LIB, 0, (void(*)())Trampoline_DI_LV_DesFunc };

void EA_GetEntry(int *arg);
static void  Trampoline_EA_GetEntry(void)
{
   EA_GetEntry((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_GetEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_GetEntry };

void EA_PutEntry(int *arg);
static void  Trampoline_EA_PutEntry(void)
{
   EA_PutEntry((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_PutEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_PutEntry };

void EA_Okay(int *arg);
static void  Trampoline_EA_Okay(void)
{
   EA_Okay((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_Okay = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_Okay };

void EA_AddFunc(int *arg);
static void  Trampoline_EA_AddFunc(void)
{
   EA_AddFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_AddFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_AddFunc };

void EA_SelectPhotoFunc(int *arg);
static void  Trampoline_EA_SelectPhotoFunc(void)
{
   EA_SelectPhotoFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_SelectPhotoFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_SelectPhotoFunc };

void EA_DownloadPhotoFunc(int *arg);
static void  Trampoline_EA_DownloadPhotoFunc(void)
{
   EA_DownloadPhotoFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_DownloadPhotoFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_DownloadPhotoFunc };

void EA_HomepageFunc(int *arg);
static void  Trampoline_EA_HomepageFunc(void)
{
   EA_HomepageFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_HomepageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_HomepageFunc };

void EA_CloseFunc(int *arg);
static void  Trampoline_EA_CloseFunc(void)
{
   EA_CloseFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_EA_CloseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_EA_CloseFunc };

void ER_SelectFunc(int *arg);
static void  Trampoline_ER_SelectFunc(void)
{
   ER_SelectFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_ER_SelectFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_ER_SelectFunc };

void ER_CloseFunc(int *arg);
static void  Trampoline_ER_CloseFunc(void)
{
   ER_CloseFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_ER_CloseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_ER_CloseFunc };

void FI_SearchFunc(void);
static void  Trampoline_FI_SearchFunc(void)
{
   FI_SearchFunc();
}
const struct EmulLibEntry Gate_FI_SearchFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_SearchFunc };

void FI_ToRuleFunc(void);
static void  Trampoline_FI_ToRuleFunc(void)
{
   FI_ToRuleFunc();
}
const struct EmulLibEntry Gate_FI_ToRuleFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_ToRuleFunc };

void FI_Open(void);
static void  Trampoline_FI_Open(void)
{
   FI_Open();
}
const struct EmulLibEntry Gate_FI_Open = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_Open };

void FI_SearchOptFunc(ULONG *arg);
static void  Trampoline_FI_SearchOptFunc(void)
{
   FI_SearchOptFunc((ULONG *)REG_A1);
}
const struct EmulLibEntry Gate_FI_SearchOptFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_SearchOptFunc };

void FI_EditFileFunc(int *arg);
static void  Trampoline_FI_EditFileFunc(void)
{
   FI_EditFileFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_FI_EditFileFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_EditFileFunc };

void FI_SwitchFunc(void);
static void  Trampoline_FI_SwitchFunc(void)
{
   FI_SwitchFunc();
}
const struct EmulLibEntry Gate_FI_SwitchFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_SwitchFunc };

void FI_ReadFunc(void);
static void  Trampoline_FI_ReadFunc(void)
{
   FI_ReadFunc();
}
const struct EmulLibEntry Gate_FI_ReadFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_ReadFunc };

void FI_SelectFunc(void);
static void  Trampoline_FI_SelectFunc(void)
{
   FI_SelectFunc();
}
const struct EmulLibEntry Gate_FI_SelectFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_SelectFunc };

void FI_Close(void);
static void  Trampoline_FI_Close(void)
{
   FI_Close();
}
const struct EmulLibEntry Gate_FI_Close = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_Close };

long FI_PO_InitRuleListFunc(Object *pop);
static long  Trampoline_FI_PO_InitRuleListFunc(void)
{
   return FI_PO_InitRuleListFunc((Object *)REG_A2);
}
const struct EmulLibEntry Gate_FI_PO_InitRuleListFunc = { TRAP_LIB, 0, (void(*)())Trampoline_FI_PO_InitRuleListFunc };

void FI_PO_FromRuleFunc(Object *pop);
static void  Trampoline_FI_PO_FromRuleFunc(void)
{
   FI_PO_FromRuleFunc((Object *)REG_A2);
}
const struct EmulLibEntry Gate_FI_PO_FromRuleFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FI_PO_FromRuleFunc };

void FO_NewSeparatorFunc(void);
static void  Trampoline_FO_NewSeparatorFunc(void)
{
   FO_NewSeparatorFunc();
}
const struct EmulLibEntry Gate_FO_NewSeparatorFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_NewSeparatorFunc };

void FO_NewFolderFunc(void);
static void  Trampoline_FO_NewFolderFunc(void)
{
   FO_NewFolderFunc();
}
const struct EmulLibEntry Gate_FO_NewFolderFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_NewFolderFunc };

void FO_EditFolderFunc(void);
static void  Trampoline_FO_EditFolderFunc(void)
{
   FO_EditFolderFunc();
}
const struct EmulLibEntry Gate_FO_EditFolderFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_EditFolderFunc };

void FO_DeleteFolderFunc(void);
static void  Trampoline_FO_DeleteFolderFunc(void)
{
   FO_DeleteFolderFunc();
}
const struct EmulLibEntry Gate_FO_DeleteFolderFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_DeleteFolderFunc };

void FO_MoveFunc(void);
static void  Trampoline_FO_MoveFunc(void)
{
   FO_MoveFunc();
}
const struct EmulLibEntry Gate_FO_MoveFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_MoveFunc };

void FO_CloseFunc(void);
static void  Trampoline_FO_CloseFunc(void)
{
   FO_CloseFunc();
}
const struct EmulLibEntry Gate_FO_CloseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_CloseFunc };

void FO_SaveFunc(void);
static void  Trampoline_FO_SaveFunc(void)
{
   FO_SaveFunc();
}
const struct EmulLibEntry Gate_FO_SaveFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_SaveFunc };

void FO_SetOrderFunc(int *arg);
static void  Trampoline_FO_SetOrderFunc(void)
{
   FO_SetOrderFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_FO_SetOrderFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_FO_SetOrderFunc };

void MA_ChangeSelectedFunc(void);
static void  Trampoline_MA_ChangeSelectedFunc(void)
{
   MA_ChangeSelectedFunc();
}
const struct EmulLibEntry Gate_MA_ChangeSelectedFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ChangeSelectedFunc };

void MA_SetMessageInfoFunc(void);
static void  Trampoline_MA_SetMessageInfoFunc(void)
{
   MA_SetMessageInfoFunc();
}
const struct EmulLibEntry Gate_MA_SetMessageInfoFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_SetMessageInfoFunc };

void MA_SetFolderInfoFunc(void);
static void  Trampoline_MA_SetFolderInfoFunc(void)
{
   MA_SetFolderInfoFunc();
}
const struct EmulLibEntry Gate_MA_SetFolderInfoFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_SetFolderInfoFunc };

void MA_ReadMessage(int *arg);
static void  Trampoline_MA_ReadMessage(void)
{
   MA_ReadMessage((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_ReadMessage = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ReadMessage };

void MA_RemoveAttachFunc(void);
static void  Trampoline_MA_RemoveAttachFunc(void)
{
   MA_RemoveAttachFunc();
}
const struct EmulLibEntry Gate_MA_RemoveAttachFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_RemoveAttachFunc };

void MA_SaveAttachFunc(void);
static void  Trampoline_MA_SaveAttachFunc(void)
{
   MA_SaveAttachFunc();
}
const struct EmulLibEntry Gate_MA_SaveAttachFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_SaveAttachFunc };

void MA_SavePrintFunc(int *arg);
static void  Trampoline_MA_SavePrintFunc(void)
{
   MA_SavePrintFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_SavePrintFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_SavePrintFunc };

void MA_NewMessageFunc(int *arg);
static void  Trampoline_MA_NewMessageFunc(void)
{
   MA_NewMessageFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_NewMessageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_NewMessageFunc };

void MA_DeleteMessageFunc(int *arg);
static void  Trampoline_MA_DeleteMessageFunc(void)
{
   MA_DeleteMessageFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_DeleteMessageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_DeleteMessageFunc };

void MA_DelKeyFunc(int *arg);
static void  Trampoline_MA_DelKeyFunc(void)
{
   MA_DelKeyFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_DelKeyFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_DelKeyFunc };

void MA_GetAddressFunc(void);
static void  Trampoline_MA_GetAddressFunc(void)
{
   MA_GetAddressFunc();
}
const struct EmulLibEntry Gate_MA_GetAddressFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_GetAddressFunc };

void MA_PopNowFunc(int *arg);
static void  Trampoline_MA_PopNowFunc(void)
{
   MA_PopNowFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_PopNowFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_PopNowFunc };

void MA_ApplyRulesFunc(int *arg);
static void  Trampoline_MA_ApplyRulesFunc(void)
{
   MA_ApplyRulesFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_ApplyRulesFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ApplyRulesFunc };

void MA_SendFunc(int *arg);
static void  Trampoline_MA_SendFunc(void)
{
   MA_SendFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_SendFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_SendFunc };

void MA_SetStatusToFunc(int *arg);
static void  Trampoline_MA_SetStatusToFunc(void)
{
   MA_SetStatusToFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_SetStatusToFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_SetStatusToFunc };

void MA_SelectAllFunc(void);
static void  Trampoline_MA_SelectAllFunc(void)
{
   MA_SelectAllFunc();
}
const struct EmulLibEntry Gate_MA_SelectAllFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_SelectAllFunc };

void MA_DeleteOldFunc(void);
static void  Trampoline_MA_DeleteOldFunc(void)
{
   MA_DeleteOldFunc();
}
const struct EmulLibEntry Gate_MA_DeleteOldFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_DeleteOldFunc };

void MA_DeleteDeletedFunc(void);
static void  Trampoline_MA_DeleteDeletedFunc(void)
{
   MA_DeleteDeletedFunc();
}
const struct EmulLibEntry Gate_MA_DeleteDeletedFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_DeleteDeletedFunc };

void MA_RescanIndexFunc(void);
static void  Trampoline_MA_RescanIndexFunc(void)
{
   MA_RescanIndexFunc();
}
const struct EmulLibEntry Gate_MA_RescanIndexFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_RescanIndexFunc };

void MA_ExportMessagesFunc(int *arg);
static void  Trampoline_MA_ExportMessagesFunc(void)
{
   MA_ExportMessagesFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_ExportMessagesFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ExportMessagesFunc };

void MA_ImportMessagesFunc(void);
static void  Trampoline_MA_ImportMessagesFunc(void)
{
   MA_ImportMessagesFunc();
}
const struct EmulLibEntry Gate_MA_ImportMessagesFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ImportMessagesFunc };

void MA_MoveMessageFunc(void);
static void  Trampoline_MA_MoveMessageFunc(void)
{
   MA_MoveMessageFunc();
}
const struct EmulLibEntry Gate_MA_MoveMessageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_MoveMessageFunc };

void MA_CopyMessageFunc(void);
static void  Trampoline_MA_CopyMessageFunc(void)
{
   MA_CopyMessageFunc();
}
const struct EmulLibEntry Gate_MA_CopyMessageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_CopyMessageFunc };

void MA_ChangeSubjectFunc(void);
static void  Trampoline_MA_ChangeSubjectFunc(void)
{
   MA_ChangeSubjectFunc();
}
const struct EmulLibEntry Gate_MA_ChangeSubjectFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ChangeSubjectFunc };

void MA_AboutMUIFunc(void);
static void  Trampoline_MA_AboutMUIFunc(void)
{
   MA_AboutMUIFunc();
}
const struct EmulLibEntry Gate_MA_AboutMUIFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_AboutMUIFunc };

void MA_CheckVersionFunc(void);
static void  Trampoline_MA_CheckVersionFunc(void)
{
   MA_CheckVersionFunc();
}
const struct EmulLibEntry Gate_MA_CheckVersionFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_CheckVersionFunc };

void MA_ShowErrorsFunc(void);
static void  Trampoline_MA_ShowErrorsFunc(void)
{
   MA_ShowErrorsFunc();
}
const struct EmulLibEntry Gate_MA_ShowErrorsFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ShowErrorsFunc };

void MA_CallRexxFunc(int *arg);
static void  Trampoline_MA_CallRexxFunc(void)
{
   MA_CallRexxFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_MA_CallRexxFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_CallRexxFunc };

void PO_Window(Object *pop, Object *win);
static void  Trampoline_PO_Window(void)
{
   PO_Window((Object *)REG_A2, (Object *)REG_A1);
}
const struct EmulLibEntry Gate_PO_Window = { TRAP_LIBNR, 0, (void(*)())Trampoline_PO_Window };

struct Folder;
struct Folder * MA_LV_FConFunc(struct Folder *fo);
static struct Folder *  Trampoline_MA_LV_FConFunc(void)
{
   return MA_LV_FConFunc((struct Folder *)REG_A1);
}
const struct EmulLibEntry Gate_MA_LV_FConFunc = { TRAP_LIB, 0, (void(*)())Trampoline_MA_LV_FConFunc };

struct Hook;
struct Mail;
long MA_LV_DspFunc(struct Hook *hook, char **array, struct Mail *entry);
static long  Trampoline_MA_LV_DspFunc(void)
{
   return MA_LV_DspFunc((struct Hook *)REG_A0, (char **)REG_A2, (struct Mail *)REG_A1);
}
const struct EmulLibEntry Gate_MA_LV_DspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_MA_LV_DspFunc };

struct NList_CompareMessage;
long MA_LV_Cmp2Func(struct NList_CompareMessage *ncm, Object *obj);
static long  Trampoline_MA_LV_Cmp2Func(void)
{
   return MA_LV_Cmp2Func((struct NList_CompareMessage *)REG_A1, (Object *)REG_A2);
}
const struct EmulLibEntry Gate_MA_LV_Cmp2Func = { TRAP_LIB, 0, (void(*)())Trampoline_MA_LV_Cmp2Func };

struct NList_CompareMessage;
long MA_LV_FCmp2Func(struct NList_CompareMessage *ncm, Object *obj);
static long  Trampoline_MA_LV_FCmp2Func(void)
{
   return MA_LV_FCmp2Func((struct NList_CompareMessage *)REG_A1, (Object *)REG_A2);
}
const struct EmulLibEntry Gate_MA_LV_FCmp2Func = { TRAP_LIB, 0, (void(*)())Trampoline_MA_LV_FCmp2Func };

void MA_FlushIndexFunc(void);
static void  Trampoline_MA_FlushIndexFunc(void)
{
   MA_FlushIndexFunc();
}
const struct EmulLibEntry Gate_MA_FlushIndexFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_FlushIndexFunc };

void MA_ChangeFolderFunc(void);
static void  Trampoline_MA_ChangeFolderFunc(void)
{
   MA_ChangeFolderFunc();
}
const struct EmulLibEntry Gate_MA_ChangeFolderFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_MA_ChangeFolderFunc };

long PO_InitFolderList(Object *pop);
static long  Trampoline_PO_InitFolderList(void)
{
   return PO_InitFolderList((Object *)REG_A2);
}
const struct EmulLibEntry Gate_PO_InitFolderList = { TRAP_LIB, 0, (void(*)())Trampoline_PO_InitFolderList };

struct Folder;
long MA_LV_FDspFunc(char **array, struct Folder *entry);
static long  Trampoline_MA_LV_FDspFunc(void)
{
   return MA_LV_FDspFunc((char **)REG_A2, (struct Folder *)REG_A1);
}
const struct EmulLibEntry Gate_MA_LV_FDspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_MA_LV_FDspFunc };

void RE_Follow(int *arg);
static void  Trampoline_RE_Follow(void)
{
   RE_Follow((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_Follow = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_Follow };

void RE_PrevNext(int *arg);
static void  Trampoline_RE_PrevNext(void)
{
   RE_PrevNext((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_PrevNext = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_PrevNext };

void RE_PrevNextPageFunc(int *arg);
static void  Trampoline_RE_PrevNextPageFunc(void)
{
   RE_PrevNextPageFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_PrevNextPageFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_PrevNextPageFunc };

void RE_MoveFunc(int *arg);
static void  Trampoline_RE_MoveFunc(void)
{
   RE_MoveFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_MoveFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_MoveFunc };

void RE_CopyFunc(int *arg);
static void  Trampoline_RE_CopyFunc(void)
{
   RE_CopyFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_CopyFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_CopyFunc };

void RE_DeleteFunc(int *arg);
static void  Trampoline_RE_DeleteFunc(void)
{
   RE_DeleteFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_DeleteFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_DeleteFunc };

void RE_PrintFunc(int *arg);
static void  Trampoline_RE_PrintFunc(void)
{
   RE_PrintFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_PrintFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_PrintFunc };

void RE_SaveFunc(int *arg);
static void  Trampoline_RE_SaveFunc(void)
{
   RE_SaveFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_SaveFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_SaveFunc };

void RE_DisplayFunc(int *arg);
static void  Trampoline_RE_DisplayFunc(void)
{
   RE_DisplayFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_DisplayFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_DisplayFunc };

void RE_SaveAllFunc(int *arg);
static void  Trampoline_RE_SaveAllFunc(void)
{
   RE_SaveAllFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_SaveAllFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_SaveAllFunc };

void RE_RemoveAttachFunc(int *arg);
static void  Trampoline_RE_RemoveAttachFunc(void)
{
   RE_RemoveAttachFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_RemoveAttachFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_RemoveAttachFunc };

void RE_NewFunc(int *arg);
static void  Trampoline_RE_NewFunc(void)
{
   RE_NewFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_NewFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_NewFunc };

void RE_GetAddressFunc(int *arg);
static void  Trampoline_RE_GetAddressFunc(void)
{
   RE_GetAddressFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_GetAddressFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_GetAddressFunc };

void RE_SetUnreadFunc(int *arg);
static void  Trampoline_RE_SetUnreadFunc(void)
{
   RE_SetUnreadFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_SetUnreadFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_SetUnreadFunc };

void RE_ChangeSubjectFunc(int *arg);
static void  Trampoline_RE_ChangeSubjectFunc(void)
{
   RE_ChangeSubjectFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_ChangeSubjectFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_ChangeSubjectFunc };

void RE_ExtractKeyFunc(int *arg);
static void  Trampoline_RE_ExtractKeyFunc(void)
{
   RE_ExtractKeyFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_ExtractKeyFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_ExtractKeyFunc };

void RE_CheckSignatureFunc(int *arg);
static void  Trampoline_RE_CheckSignatureFunc(void)
{
   RE_CheckSignatureFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_CheckSignatureFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_CheckSignatureFunc };

void RE_SaveDecryptedFunc(int *arg);
static void  Trampoline_RE_SaveDecryptedFunc(void)
{
   RE_SaveDecryptedFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_SaveDecryptedFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_SaveDecryptedFunc };

struct ClickMessage;
BOOL RE_DoubleClickFunc(struct ClickMessage *clickmsg, APTR obj);
static BOOL  Trampoline_RE_DoubleClickFunc(void)
{
   return RE_DoubleClickFunc((struct ClickMessage *)REG_A1, (APTR)REG_A2);
}
const struct EmulLibEntry Gate_RE_DoubleClickFunc = { TRAP_LIB, 0, (void(*)())Trampoline_RE_DoubleClickFunc };

void RE_ShowEnvFunc(int *arg);
static void  Trampoline_RE_ShowEnvFunc(void)
{
   RE_ShowEnvFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_ShowEnvFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_ShowEnvFunc };

struct Part;
long RE_LV_AttachDspFunc(char **array, struct Part *entry);
static long  Trampoline_RE_LV_AttachDspFunc(void)
{
   return RE_LV_AttachDspFunc((char **)REG_A2, (struct Part *)REG_A1);
}
const struct EmulLibEntry Gate_RE_LV_AttachDspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_RE_LV_AttachDspFunc };

void RE_CloseFunc(int *arg);
static void  Trampoline_RE_CloseFunc(void)
{
   RE_CloseFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_RE_CloseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_RE_CloseFunc };

long RE_LV_HDspFunc(char **array, char *entry);
static long  Trampoline_RE_LV_HDspFunc(void)
{
   return RE_LV_HDspFunc((char **)REG_A2, (char *)REG_A1);
}
const struct EmulLibEntry Gate_RE_LV_HDspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_RE_LV_HDspFunc };

void TR_ChangeStatusFunc(int *arg);
static void  Trampoline_TR_ChangeStatusFunc(void)
{
   TR_ChangeStatusFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_TR_ChangeStatusFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_TR_ChangeStatusFunc };

void TR_AbortIMPORTFunc(void);
static void  Trampoline_TR_AbortIMPORTFunc(void)
{
   TR_AbortIMPORTFunc();
}
const struct EmulLibEntry Gate_TR_AbortIMPORTFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_TR_AbortIMPORTFunc };

void TR_ProcessIMPORTFunc(void);
static void  Trampoline_TR_ProcessIMPORTFunc(void)
{
   TR_ProcessIMPORTFunc();
}
const struct EmulLibEntry Gate_TR_ProcessIMPORTFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_TR_ProcessIMPORTFunc };

void TR_AbortGETFunc(void);
static void  Trampoline_TR_AbortGETFunc(void)
{
   TR_AbortGETFunc();
}
const struct EmulLibEntry Gate_TR_AbortGETFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_TR_AbortGETFunc };

void TR_ProcessGETFunc(void);
static void  Trampoline_TR_ProcessGETFunc(void)
{
   TR_ProcessGETFunc();
}
const struct EmulLibEntry Gate_TR_ProcessGETFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_TR_ProcessGETFunc };

void TR_GetMessageInfoFunc(void);
static void  Trampoline_TR_GetMessageInfoFunc(void)
{
   TR_GetMessageInfoFunc();
}
const struct EmulLibEntry Gate_TR_GetMessageInfoFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_TR_GetMessageInfoFunc };

void TR_PauseFunc(int *arg);
static void  Trampoline_TR_PauseFunc(void)
{
   TR_PauseFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_TR_PauseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_TR_PauseFunc };

struct Hook;
struct Mail;
long TR_LV_DspFunc(struct Hook *hook, char **array, struct Mail *entry);
static long  Trampoline_TR_LV_DspFunc(void)
{
   return TR_LV_DspFunc((struct Hook *)REG_A0, (char **)REG_A2, (struct Mail *)REG_A1);
}
const struct EmulLibEntry Gate_TR_LV_DspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_TR_LV_DspFunc };

void US_DelFunc(void);
static void  Trampoline_US_DelFunc(void)
{
   US_DelFunc();
}
const struct EmulLibEntry Gate_US_DelFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_US_DelFunc };

void US_AddFunc(void);
static void  Trampoline_US_AddFunc(void)
{
   US_AddFunc();
}
const struct EmulLibEntry Gate_US_AddFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_US_AddFunc };

void US_OpenFunc(void);
static void  Trampoline_US_OpenFunc(void)
{
   US_OpenFunc();
}
const struct EmulLibEntry Gate_US_OpenFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_US_OpenFunc };

void US_CloseFunc(void);
static void  Trampoline_US_CloseFunc(void)
{
   US_CloseFunc();
}
const struct EmulLibEntry Gate_US_CloseFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_US_CloseFunc };

void US_GetUSEntryFunc(void);
static void  Trampoline_US_GetUSEntryFunc(void)
{
   US_GetUSEntryFunc();
}
const struct EmulLibEntry Gate_US_GetUSEntryFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_US_GetUSEntryFunc };

void US_PutUSEntryFunc(void);
static void  Trampoline_US_PutUSEntryFunc(void)
{
   US_PutUSEntryFunc();
}
const struct EmulLibEntry Gate_US_PutUSEntryFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_US_PutUSEntryFunc };

struct User;
struct User * US_LV_ConFunc(struct User *user);
static struct User *  Trampoline_US_LV_ConFunc(void)
{
   return US_LV_ConFunc((struct User *)REG_A1);
}
const struct EmulLibEntry Gate_US_LV_ConFunc = { TRAP_LIB, 0, (void(*)())Trampoline_US_LV_ConFunc };

struct User;
long US_LV_DspFunc(char **array, struct User *entry);
static long  Trampoline_US_LV_DspFunc(void)
{
   return US_LV_DspFunc((char **)REG_A2, (struct User *)REG_A1);
}
const struct EmulLibEntry Gate_US_LV_DspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_US_LV_DspFunc };

long GeneralDesFunc(void *entry);
static long  Trampoline_GeneralDesFunc(void)
{
   return GeneralDesFunc((void *)REG_A1);
}
const struct EmulLibEntry Gate_GeneralDesFunc = { TRAP_LIB, 0, (void(*)())Trampoline_GeneralDesFunc };

void PO_SetPublicKey(APTR string, APTR pop);
static void  Trampoline_PO_SetPublicKey(void)
{
   PO_SetPublicKey((APTR)REG_A1, (APTR)REG_A2);
}
const struct EmulLibEntry Gate_PO_SetPublicKey = { TRAP_LIBNR, 0, (void(*)())Trampoline_PO_SetPublicKey };

long PO_ListPublicKeys(APTR string, APTR pop);
static long  Trampoline_PO_ListPublicKeys(void)
{
   return PO_ListPublicKeys((APTR)REG_A1, (APTR)REG_A2);
}
const struct EmulLibEntry Gate_PO_ListPublicKeys = { TRAP_LIB, 0, (void(*)())Trampoline_PO_ListPublicKeys };

void DisposeModuleFunc(void **arg);
static void  Trampoline_DisposeModuleFunc(void)
{
   DisposeModuleFunc((void **)REG_A1);
}
const struct EmulLibEntry Gate_DisposeModuleFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_DisposeModuleFunc };

struct Hook;
struct Locale;
void putCharFunc( struct Hook *hook,  char c,  struct Locale *locale);
static void  Trampoline_putCharFunc(void)
{
   putCharFunc((struct Hook *)REG_A0, (char)REG_A1, (struct Locale *)REG_A2);
}
const struct EmulLibEntry Gate_putCharFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_putCharFunc };

void WR_VerifyAutoFunc(int *arg);
static void  Trampoline_WR_VerifyAutoFunc(void)
{
   WR_VerifyAutoFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_VerifyAutoFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_VerifyAutoFunc };

void WR_VerifyManualFunc(int *arg);
static void  Trampoline_WR_VerifyManualFunc(void)
{
   WR_VerifyManualFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_VerifyManualFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_VerifyManualFunc };

void WR_GetFileEntry(int *arg);
static void  Trampoline_WR_GetFileEntry(void)
{
   WR_GetFileEntry((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_GetFileEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_GetFileEntry };

void WR_PutFileEntry(int *arg);
static void  Trampoline_WR_PutFileEntry(void)
{
   WR_PutFileEntry((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_PutFileEntry = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_PutFileEntry };

void WR_NewMailFunc(int *arg);
static void  Trampoline_WR_NewMailFunc(void)
{
   WR_NewMailFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_NewMailFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_NewMailFunc };

void WR_CancelFunc(int *arg);
static void  Trampoline_WR_CancelFunc(void)
{
   WR_CancelFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_CancelFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_CancelFunc };

void WR_SaveAsFunc(int *arg);
static void  Trampoline_WR_SaveAsFunc(void)
{
   WR_SaveAsFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_SaveAsFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_SaveAsFunc };

void WR_Edit(int *arg);
static void  Trampoline_WR_Edit(void)
{
   WR_Edit((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_Edit = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_Edit };

void WR_AddFileFunc(int *arg);
static void  Trampoline_WR_AddFileFunc(void)
{
   WR_AddFileFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_AddFileFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_AddFileFunc };

void WR_AddArchiveFunc(int *arg);
static void  Trampoline_WR_AddArchiveFunc(void)
{
   WR_AddArchiveFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_AddArchiveFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_AddArchiveFunc };

void WR_DisplayFile(int *arg);
static void  Trampoline_WR_DisplayFile(void)
{
   WR_DisplayFile((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_DisplayFile = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_DisplayFile };

void WR_ChangeSignatureFunc(int *arg);
static void  Trampoline_WR_ChangeSignatureFunc(void)
{
   WR_ChangeSignatureFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_ChangeSignatureFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_ChangeSignatureFunc };

void WR_InsertSeparatorFunc(int *arg);
static void  Trampoline_WR_InsertSeparatorFunc(void)
{
   WR_InsertSeparatorFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_InsertSeparatorFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_InsertSeparatorFunc };

void WR_EditorCmd(int *arg);
static void  Trampoline_WR_EditorCmd(void)
{
   WR_EditorCmd((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_EditorCmd = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_EditorCmd };

void WR_AddClipboardFunc(int *arg);
static void  Trampoline_WR_AddClipboardFunc(void)
{
   WR_AddClipboardFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_AddClipboardFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_AddClipboardFunc };

void WR_AddPGPKeyFunc(int *arg);
static void  Trampoline_WR_AddPGPKeyFunc(void)
{
   WR_AddPGPKeyFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_AddPGPKeyFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_AddPGPKeyFunc };

void WR_UpdateWTitleFunc(int *arg);
static void  Trampoline_WR_UpdateWTitleFunc(void)
{
   WR_UpdateWTitleFunc((int *)REG_A1);
}
const struct EmulLibEntry Gate_WR_UpdateWTitleFunc = { TRAP_LIBNR, 0, (void(*)())Trampoline_WR_UpdateWTitleFunc };

LONG WR_AppFunc(ULONG *arg);
static LONG  Trampoline_WR_AppFunc(void)
{
   return WR_AppFunc((ULONG *)REG_A1);
}
const struct EmulLibEntry Gate_WR_AppFunc = { TRAP_LIB, 0, (void(*)())Trampoline_WR_AppFunc };

struct Attach;
struct Attach * WR_LV_ConFunc(struct Attach *attach);
static struct Attach *  Trampoline_WR_LV_ConFunc(void)
{
   return WR_LV_ConFunc((struct Attach *)REG_A1);
}
const struct EmulLibEntry Gate_WR_LV_ConFunc = { TRAP_LIB, 0, (void(*)())Trampoline_WR_LV_ConFunc };

struct Attach;
long WR_LV_DspFunc(char **array, struct Attach *entry);
static long  Trampoline_WR_LV_DspFunc(void)
{
   return WR_LV_DspFunc((char **)REG_A2, (struct Attach *)REG_A1);
}
const struct EmulLibEntry Gate_WR_LV_DspFunc = { TRAP_LIB, 0, (void(*)())Trampoline_WR_LV_DspFunc };

