/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 4605$
 * $Date: 2011-11-15$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV    4605
#define SVN_REVSTR  "4605"
#define SVN_REVDATE  "2011-11-15"
#define SVN_REVSTAMP  20111115L
#define SVN_REVMODIFIED  0

#endif /* SVN_REV_H */
