#ifndef INLINE4_GUIGFX_H
#define INLINE4_GUIGFX_H

/*
** This file was auto generated by idltool 51.3.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline macros for Interface "main" */
#define MakePictureA(array, width, height, tags) IGuiGFX->MakePictureA(array, width, height, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define MakePicture(array, width, ...) IGuiGFX->MakePicture(array, width, __VA_ARGS__) 
#endif
#define LoadPictureA(filename, tags) IGuiGFX->LoadPictureA(filename, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define LoadPicture(...) IGuiGFX->LoadPicture(__VA_ARGS__) 
#endif
#define ReadPictureA(a0arg, colormap, x, y, width, height, tags) IGuiGFX->ReadPictureA(a0arg, colormap, x, y, width, height, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define ReadPicture(a0arg, colormap, x, y, width, ...) IGuiGFX->ReadPicture(a0arg, colormap, x, y, width, __VA_ARGS__) 
#endif
#define ClonePictureA(pic, tags) IGuiGFX->ClonePictureA(pic, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define ClonePicture(...) IGuiGFX->ClonePicture(__VA_ARGS__) 
#endif
#define DeletePicture(pic) IGuiGFX->DeletePicture(pic) 
#define UpdatePicture(pic) IGuiGFX->UpdatePicture(pic) 
#define AddPictureA(psm, pic, tags) IGuiGFX->AddPictureA(psm, pic, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define AddPicture(psm, ...) IGuiGFX->AddPicture(psm, __VA_ARGS__) 
#endif
#define AddPaletteA(psm, palette, tags) IGuiGFX->AddPaletteA(psm, palette, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define AddPalette(psm, ...) IGuiGFX->AddPalette(psm, __VA_ARGS__) 
#endif
#define AddPixelArrayA(psm, array, width, height, tags) IGuiGFX->AddPixelArrayA(psm, array, width, height, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define AddPixelArray(psm, array, width, ...) IGuiGFX->AddPixelArray(psm, array, width, __VA_ARGS__) 
#endif
#define RemColorHandle(colorhandle) IGuiGFX->RemColorHandle(colorhandle) 
#define CreatePenShareMapA(tags) IGuiGFX->CreatePenShareMapA(tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define CreatePenShareMap(...) IGuiGFX->CreatePenShareMap(__VA_ARGS__) 
#endif
#define DeletePenShareMap(psm) IGuiGFX->DeletePenShareMap(psm) 
#define ObtainDrawHandleA(psm, a1arg, cm, tags) IGuiGFX->ObtainDrawHandleA(psm, a1arg, cm, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define ObtainDrawHandle(psm, a1arg, ...) IGuiGFX->ObtainDrawHandle(psm, a1arg, __VA_ARGS__) 
#endif
#define ReleaseDrawHandle(drawhandle) IGuiGFX->ReleaseDrawHandle(drawhandle) 
#define DrawPictureA(drawhandle, pic, x, y, tags) IGuiGFX->DrawPictureA(drawhandle, pic, x, y, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define DrawPicture(drawhandle, pic, x, ...) IGuiGFX->DrawPicture(drawhandle, pic, x, __VA_ARGS__) 
#endif
#define MapPaletteA(drawhandle, palette, pentab, tags) IGuiGFX->MapPaletteA(drawhandle, palette, pentab, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define MapPalette(drawhandle, palette, ...) IGuiGFX->MapPalette(drawhandle, palette, __VA_ARGS__) 
#endif
#define MapPenA(drawhandle, rgb, tags) IGuiGFX->MapPenA(drawhandle, rgb, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define MapPen(drawhandle, ...) IGuiGFX->MapPen(drawhandle, __VA_ARGS__) 
#endif
#define CreatePictureBitMapA(drawhandle, pic, tags) IGuiGFX->CreatePictureBitMapA(drawhandle, pic, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define CreatePictureBitMap(drawhandle, ...) IGuiGFX->CreatePictureBitMap(drawhandle, __VA_ARGS__) 
#endif
#define DoPictureMethodA(pic, method, arguments) IGuiGFX->DoPictureMethodA(pic, method, arguments) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define DoPictureMethod(pic, ...) IGuiGFX->DoPictureMethod(pic, __VA_ARGS__) 
#endif
#define GetPictureAttrsA(pic, tags) IGuiGFX->GetPictureAttrsA(pic, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define GetPictureAttrs(...) IGuiGFX->GetPictureAttrs(__VA_ARGS__) 
#endif
#define LockPictureA(pic, mode, args) IGuiGFX->LockPictureA(pic, mode, args) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define LockPicture(pic, ...) IGuiGFX->LockPicture(pic, __VA_ARGS__) 
#endif
#define UnLockPicture(pic, mode) IGuiGFX->UnLockPicture(pic, mode) 
#define IsPictureA(filename, tags) IGuiGFX->IsPictureA(filename, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define IsPicture(...) IGuiGFX->IsPicture(__VA_ARGS__) 
#endif
#define CreateDirectDrawHandleA(drawhandle, sw, sh, dw, dh, tags) IGuiGFX->CreateDirectDrawHandleA(drawhandle, sw, sh, dw, dh, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define CreateDirectDrawHandle(drawhandle, sw, sh, dw, ...) IGuiGFX->CreateDirectDrawHandle(drawhandle, sw, sh, dw, __VA_ARGS__) 
#endif
#define DeleteDirectDrawHandle(ddh) IGuiGFX->DeleteDirectDrawHandle(ddh) 
#define DirectDrawTrueColorA(ddh, array, x, y, tags) IGuiGFX->DirectDrawTrueColorA(ddh, array, x, y, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define DirectDrawTrueColor(ddh, array, x, ...) IGuiGFX->DirectDrawTrueColor(ddh, array, x, __VA_ARGS__) 
#endif
#define CreatePictureMaskA(pic, mask, maskwidth, tags) IGuiGFX->CreatePictureMaskA(pic, mask, maskwidth, tags) 
#if !defined(__cplusplus) && (__GNUC__ >= 3    \
    || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95) \
    || (__STDC_VERSION__ && __STDC_VERSION__ >= 199901L))
#define CreatePictureMask(pic, mask, ...) IGuiGFX->CreatePictureMask(pic, mask, __VA_ARGS__) 
#endif

#endif /* INLINE4_GUIGFX_H */
