#ifndef INLINE4_XADMASTER_H
#define INLINE4_XADMASTER_H

/*
** This file was auto generated by idltool 52.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_XADMASTER_H
#include <libraries/xadmaster.h>
#endif
#include <interfaces/xadmaster.h>

/* Inline macros for Interface "main" */
#define xadAllocObjectA(type, tags) IxadMaster->xadAllocObjectA((type), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadAllocObject(...) IxadMaster->xadAllocObject(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadAllocObject(vargs...) IxadMaster->xadAllocObject(## vargs) 
#endif
#define xadFreeObjectA(object, tags) IxadMaster->xadFreeObjectA((object), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadFreeObject(...) IxadMaster->xadFreeObject(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadFreeObject(vargs...) IxadMaster->xadFreeObject(## vargs) 
#endif
#define xadRecogFileA(size, memory, tags) IxadMaster->xadRecogFileA((size), (memory), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadRecogFile(size, ...) IxadMaster->xadRecogFile((size), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadRecogFile(size, vargs...) IxadMaster->xadRecogFile(size, ## vargs) 
#endif
#define xadGetInfoA(ai, tags) IxadMaster->xadGetInfoA((ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadGetInfo(...) IxadMaster->xadGetInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadGetInfo(vargs...) IxadMaster->xadGetInfo(## vargs) 
#endif
#define xadFreeInfo(ai) IxadMaster->xadFreeInfo((ai)) 
#define xadFileUnArcA(ai, tags) IxadMaster->xadFileUnArcA((ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadFileUnArc(...) IxadMaster->xadFileUnArc(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadFileUnArc(vargs...) IxadMaster->xadFileUnArc(## vargs) 
#endif
#define xadDiskUnArcA(ai, tags) IxadMaster->xadDiskUnArcA((ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadDiskUnArc(...) IxadMaster->xadDiskUnArc(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadDiskUnArc(vargs...) IxadMaster->xadDiskUnArc(## vargs) 
#endif
#define xadGetErrorText(errnum) IxadMaster->xadGetErrorText((errnum)) 
#define xadGetClientInfo() IxadMaster->xadGetClientInfo() 
#define xadHookAccess(command, data, buffer, ai) IxadMaster->xadHookAccess((command), (data), (buffer), (ai)) 
#define xadConvertDatesA(tags) IxadMaster->xadConvertDatesA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadConvertDates(...) IxadMaster->xadConvertDates(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadConvertDates(...) IxadMaster->xadConvertDates(## vargs) 
#endif
#define xadCalcCRC16(id, init, size, buffer) IxadMaster->xadCalcCRC16((id), (init), (size), (buffer)) 
#define xadCalcCRC32(id, init, size, buffer) IxadMaster->xadCalcCRC32((id), (init), (size), (buffer)) 
#define xadAllocVec(size, flags) IxadMaster->xadAllocVec((size), (flags)) 
#define xadCopyMem(src, dest, size) IxadMaster->xadCopyMem((src), (dest), (size)) 
#define xadHookTagAccessA(command, data, buffer, ai, tags) IxadMaster->xadHookTagAccessA((command), (data), (buffer), (ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadHookTagAccess(command, data, buffer, ...) IxadMaster->xadHookTagAccess((command), (data), (buffer), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadHookTagAccess(command, data, buffer, vargs...) IxadMaster->xadHookTagAccess(command, data, buffer, ## vargs) 
#endif
#define xadConvertProtectionA(tags) IxadMaster->xadConvertProtectionA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadConvertProtection(...) IxadMaster->xadConvertProtection(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadConvertProtection(...) IxadMaster->xadConvertProtection(## vargs) 
#endif
#define xadGetDiskInfoA(ai, tags) IxadMaster->xadGetDiskInfoA((ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadGetDiskInfo(...) IxadMaster->xadGetDiskInfo(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadGetDiskInfo(vargs...) IxadMaster->xadGetDiskInfo(## vargs) 
#endif
#define xadDiskFileUnArcA(ai, tags) IxadMaster->xadDiskFileUnArcA((ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadDiskFileUnArc(...) IxadMaster->xadDiskFileUnArc(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadDiskFileUnArc(vargs...) IxadMaster->xadDiskFileUnArc(## vargs) 
#endif
#define xadGetHookAccessA(ai, tags) IxadMaster->xadGetHookAccessA((ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadGetHookAccess(...) IxadMaster->xadGetHookAccess(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadGetHookAccess(vargs...) IxadMaster->xadGetHookAccess(## vargs) 
#endif
#define xadFreeHookAccessA(ai, tags) IxadMaster->xadFreeHookAccessA((ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadFreeHookAccess(...) IxadMaster->xadFreeHookAccess(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadFreeHookAccess(vargs...) IxadMaster->xadFreeHookAccess(## vargs) 
#endif
#define xadAddFileEntryA(fi, ai, tags) IxadMaster->xadAddFileEntryA((fi), (ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadAddFileEntry(fi, ...) IxadMaster->xadAddFileEntry((fi), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadAddFileEntry(fi, vargs...) IxadMaster->xadAddFileEntry(fi, ## vargs) 
#endif
#define xadAddDiskEntryA(di, ai, tags) IxadMaster->xadAddDiskEntryA((di), (ai), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadAddDiskEntry(di, ...) IxadMaster->xadAddDiskEntry((di), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadAddDiskEntry(di, vargs...) IxadMaster->xadAddDiskEntry(di, ## vargs) 
#endif
#define xadGetFilenameA(buffersize, buffer, path, name, tags) IxadMaster->xadGetFilenameA((buffersize), (buffer), (path), (name), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadGetFilename(buffersize, buffer, path, ...) IxadMaster->xadGetFilename((buffersize), (buffer), (path), __VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadGetFilename(buffersize, buffer, path, vargs...) IxadMaster->xadGetFilename(buffersize, buffer, path, ## vargs) 
#endif
#define xadConvertNameA(charset, tags) IxadMaster->xadConvertNameA((charset), (tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadConvertName(...) IxadMaster->xadConvertName(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadConvertName(vargs...) IxadMaster->xadConvertName(## vargs) 
#endif
#define xadGetDefaultNameA(tags) IxadMaster->xadGetDefaultNameA((tags)) 
#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || (__GNUC__ >= 3)
#define xadGetDefaultName(...) IxadMaster->xadGetDefaultName(__VA_ARGS__) 
#elif (__GNUC__ == 2 && __GNUC_MINOR__ >= 95)
#define xadGetDefaultName(...) IxadMaster->xadGetDefaultName(## vargs) 
#endif
#define xadGetSystemInfo() IxadMaster->xadGetSystemInfo() 

#endif /* INLINE4_XADMASTER_H */
