#ifndef INLINE4_XPKMASTER_H
#define INLINE4_XPKMASTER_H

/*
** This file was auto generated by idltool 50.10.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef XPK_XPK_H
#include <xpk/xpk.h>
#endif

/* Inline macros for Interface "main" */
#define XpkExamine(fib, tags) IXpk->XpkExamine(fib, tags) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define XpkExamineTags(...) IXpk->XpkExamineTags(__VA_ARGS__) 
#endif
#define XpkPack(tags) IXpk->XpkPack(tags) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define XpkPackTags(...) IXpk->XpkPackTags(__VA_ARGS__) 
#endif
#define XpkUnpack(tags) IXpk->XpkUnpack(tags) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define XpkUnpackTags(...) IXpk->XpkUnpackTags(__VA_ARGS__) 
#endif
#define XpkOpen(xbuf, tags) IXpk->XpkOpen(xbuf, tags) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define XpkOpenTags(...) IXpk->XpkOpenTags(__VA_ARGS__) 
#endif
#define XpkRead(xbuf, buf, len) IXpk->XpkRead(xbuf, buf, len) 
#define XpkWrite(xbuf, buf, len) IXpk->XpkWrite(xbuf, buf, len) 
#define XpkSeek(xbuf, len, mode) IXpk->XpkSeek(xbuf, len, mode) 
#define XpkClose(xbuf) IXpk->XpkClose(xbuf) 
#define XpkQuery(tags) IXpk->XpkQuery(tags) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define XpkQueryTags(...) IXpk->XpkQueryTags(__VA_ARGS__) 
#endif
#define XpkAllocObject(type, tags) IXpk->XpkAllocObject(type, tags) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define XpkAllocObjectTags(...) IXpk->XpkAllocObjectTags(__VA_ARGS__) 
#endif
#define XpkFreeObject(type, object) IXpk->XpkFreeObject(type, object) 
#define XpkPrintFault(code, header) IXpk->XpkPrintFault(code, header) 
#define XpkFault(code, header, buffer, size) IXpk->XpkFault(code, header, buffer, size) 
#define XpkPassRequest(tags) IXpk->XpkPassRequest(tags) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define XpkPassRequestTags(...) IXpk->XpkPassRequestTags(__VA_ARGS__) 
#endif

#endif /* INLINE4_XPKMASTER_H */
