#ifndef CMANAGER_INTERFACE_DEF_H
#define CMANAGER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.10.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


struct CManagerIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct CManagerIFace *Self);
	ULONG APICALL (*Release)(struct CManagerIFace *Self);
	void APICALL (*Expunge)(struct CManagerIFace *Self);
	struct Interface * APICALL (*Clone)(struct CManagerIFace *Self);
	APTR APICALL (*CM_StartManager)(struct CManagerIFace *Self, STRPTR par1, STRPTR last);
	BOOL APICALL (*CM_LoadData)(struct CManagerIFace *Self, STRPTR par1, struct CMData * par2, STRPTR last);
	void APICALL (*CM_SaveData)(struct CManagerIFace *Self, STRPTR par1, struct CMData * par2, STRPTR last);
	void APICALL (*CM_FreeData)(struct CManagerIFace *Self, struct CMData * last);
	struct CMGroup * APICALL (*CM_GetParent)(struct CManagerIFace *Self, struct CMGroup * par1, struct CMGroup * last);
	APTR APICALL (*CM_AllocEntry)(struct CManagerIFace *Self, ULONG last);
	void APICALL (*CM_FreeEntry)(struct CManagerIFace *Self, APTR last);
	void APICALL (*CM_FreeHandle)(struct CManagerIFace *Self, APTR par1, BOOL last);
	APTR APICALL (*CM_GetEntry)(struct CManagerIFace *Self, APTR par1, ULONG last);
	struct BitMap * APICALL (*CM_CreateBitMap)(struct CManagerIFace *Self, ULONG par1, ULONG par2, ULONG par3, ULONG par4, struct BitMap * last);
	void APICALL (*CM_DeleteBitMap)(struct CManagerIFace *Self, struct BitMap * last);
	BOOL APICALL (*CM_AddEntry)(struct CManagerIFace *Self, APTR last);
	void APICALL (*CM_FreeList)(struct CManagerIFace *Self, struct MinList * last);
};

#endif /* CMANAGER_INTERFACE_DEF_H */
