#ifndef OPENURL_INTERFACE_DEF_H
#define OPENURL_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.10.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_OPENURL_H
#include <libraries/openurl.h>
#endif

struct OpenURLIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct OpenURLIFace *Self);
	ULONG APICALL (*Release)(struct OpenURLIFace *Self);
	void APICALL (*Expunge)(struct OpenURLIFace *Self);
	struct Interface * APICALL (*Clone)(struct OpenURLIFace *Self);
	BOOL APICALL (*URL_OpenA)(struct OpenURLIFace *Self, STRPTR par1, struct TagItem * last);
	BOOL APICALL (*URL_Open)(struct OpenURLIFace *Self, STRPTR par1, ...);
	struct URL_Prefs * APICALL (*URL_GetPrefs)(struct OpenURLIFace *Self);
	VOID APICALL (*URL_FreePrefs)(struct OpenURLIFace *Self, struct URL_Prefs * last);
	BOOL APICALL (*URL_SetPrefs)(struct OpenURLIFace *Self, struct URL_Prefs * par1, BOOL last);
	struct URL_Prefs * APICALL (*URL_GetDefaultPrefs)(struct OpenURLIFace *Self);
	BOOL APICALL (*URL_LaunchPrefsApp)(struct OpenURLIFace *Self);
};

#endif /* OPENURL_INTERFACE_DEF_H */
