#pragma libcall PopupMenuBase PM_MakeMenuA 1e 901
#pragma tagcall PopupMenuBase PM_MakeMenu 1e 901
#pragma libcall PopupMenuBase PM_MakeItemA 24 901
#pragma tagcall PopupMenuBase PM_MakeItem 24 901
#pragma libcall PopupMenuBase PM_FreePopupMenu 2a 901
#pragma libcall PopupMenuBase PM_OpenPopupMenuA 30 a902
#pragma tagcall PopupMenuBase PM_OpenPopupMenu 30 a902
#pragma libcall PopupMenuBase PM_MakeIDListA 36 901
#pragma tagcall PopupMenuBase PM_MakeIDList 36 901
#pragma libcall PopupMenuBase PM_ItemChecked 3c 1902
#pragma libcall PopupMenuBase PM_GetItemAttrsA 42 9a02
#pragma tagcall PopupMenuBase PM_GetItemAttrs 42 9a02
#pragma libcall PopupMenuBase PM_SetItemAttrsA 48 9a02
#pragma tagcall PopupMenuBase PM_SetItemAttrs 48 9a02
#pragma libcall PopupMenuBase PM_FindItem 4e 1902
#pragma libcall PopupMenuBase PM_AlterState 54 1a903
#pragma libcall PopupMenuBase PM_FilterIMsgA 5a dba904
#pragma tagcall PopupMenuBase PM_FilterIMsg 5a dba904
#pragma libcall PopupMenuBase PM_ExLstA 60 901
#pragma tagcall PopupMenuBase PM_ExLst 60 901
#pragma libcall PopupMenuBase PM_InsertMenuItemA 6c 9802
#pragma tagcall PopupMenuBase PM_InsertMenuItem 6c 9802
#pragma libcall PopupMenuBase PM_RemoveMenuItem 72 9802
#pragma libcall PopupMenuBase PM_AbortHook 78 801
#pragma libcall PopupMenuBase PM_GetVersion 7e 0
#pragma libcall PopupMenuBase PM_ReloadPrefs 84 0
#pragma libcall PopupMenuBase PM_LayoutMenuA 8a a9803
#pragma tagcall PopupMenuBase PM_LayoutMenu 8a a9803
#pragma libcall PopupMenuBase PM_FreeIDList 96 801
