#ifndef INLINE4_CMANAGER_H
#define INLINE4_CMANAGER_H

/*
** This file was auto generated by idltool 50.10.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline macros for Interface "main" */
#define CM_StartManager(par1, last) ICManager->CM_StartManager(par1, last) 
#define CM_LoadData(par1, par2, last) ICManager->CM_LoadData(par1, par2, last) 
#define CM_SaveData(par1, par2, last) ICManager->CM_SaveData(par1, par2, last) 
#define CM_FreeData(last) ICManager->CM_FreeData(last) 
#define CM_GetParent(par1, last) ICManager->CM_GetParent(par1, last) 
#define CM_AllocEntry(last) ICManager->CM_AllocEntry(last) 
#define CM_FreeEntry(last) ICManager->CM_FreeEntry(last) 
#define CM_FreeHandle(par1, last) ICManager->CM_FreeHandle(par1, last) 
#define CM_GetEntry(par1, last) ICManager->CM_GetEntry(par1, last) 
#define CM_CreateBitMap(par1, par2, par3, par4, last) ICManager->CM_CreateBitMap(par1, par2, par3, par4, last) 
#define CM_DeleteBitMap(last) ICManager->CM_DeleteBitMap(last) 
#define CM_AddEntry(last) ICManager->CM_AddEntry(last) 
#define CM_FreeList(last) ICManager->CM_FreeList(last) 

#endif /* INLINE4_CMANAGER_H */
