#ifndef INLINE4_CMANAGER_H
#define INLINE4_CMANAGER_H

/*
** This file was auto generated by idltool 50.9.
**
** It provides compatibility to OS3 style library
** calls by substituting function names.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline substitutions for Interface "main" */
#define CM_StartManager ICManager->CM_StartManager
#define CM_LoadData ICManager->CM_LoadData
#define CM_SaveData ICManager->CM_SaveData
#define CM_FreeData ICManager->CM_FreeData
#define CM_GetParent ICManager->CM_GetParent
#define CM_AllocEntry ICManager->CM_AllocEntry
#define CM_FreeEntry ICManager->CM_FreeEntry
#define CM_FreeHandle ICManager->CM_FreeHandle
#define CM_GetEntry ICManager->CM_GetEntry
#define CM_CreateBitMap ICManager->CM_CreateBitMap
#define CM_DeleteBitMap ICManager->CM_DeleteBitMap
#define CM_AddEntry ICManager->CM_AddEntry
#define CM_FreeList ICManager->CM_FreeList

#endif /* INLINE4_CMANAGER_H */
