#ifndef INLINE4_GENESIS_H
#define INLINE4_GENESIS_H

/*
** This file was auto generated by idltool 50.9.
**
** It provides compatibility to OS3 style library
** calls by substituting function names.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline substitutions for Interface "main" */
#define GetFileSize IGenesis->GetFileSize
#define ParseConfig IGenesis->ParseConfig
#define ParseNext IGenesis->ParseNext
#define ParseNextLine IGenesis->ParseNextLine
#define ParseEnd IGenesis->ParseEnd
#define ReallocCopy IGenesis->ReallocCopy
#define FreeUser IGenesis->FreeUser
#define GetUserName IGenesis->GetUserName
#define GetUser IGenesis->GetUser
#define GetGlobalUser IGenesis->GetGlobalUser
#define SetGlobalUser IGenesis->SetGlobalUser
#define ClearUserList IGenesis->ClearUserList
#define ReloadUserList IGenesis->ReloadUserList
#define ReadFile IGenesis->ReadFile
#define WriteFile IGenesis->WriteFile
#define IsOnline IGenesis->IsOnline

#endif /* INLINE4_GENESIS_H */
