#ifndef INLINE4_MIAMI_H
#define INLINE4_MIAMI_H

/*
** This file was auto generated by idltool 50.9.
**
** It provides compatibility to OS3 style library
** calls by substituting function names.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline substitutions for Interface "main" */
#define MiamiSysCtl IMiami->MiamiSysCtl
#define MiamiDisallowDNS IMiami->MiamiDisallowDNS
#define MiamiGetPid IMiami->MiamiGetPid
#define MiamiPFAddHook IMiami->MiamiPFAddHook
#define MiamiPFRemoveHook IMiami->MiamiPFRemoveHook
#define MiamiGetHardwareLen IMiami->MiamiGetHardwareLen
#define MiamiOpenSSL IMiami->MiamiOpenSSL
#define MiamiCloseSSL IMiami->MiamiCloseSSL
#define MiamiSetSocksConn IMiami->MiamiSetSocksConn
#define MiamiIsOnline IMiami->MiamiIsOnline
#define MiamiOnOffline IMiami->MiamiOnOffline
#define inet_ntop IMiami->inet_ntop
#define inet_aton IMiami->inet_aton
#define inet_pton IMiami->inet_pton
#define gethostbyname2 IMiami->gethostbyname2
#define gai_strerror IMiami->gai_strerror
#define freeaddrinfo IMiami->freeaddrinfo
#define getaddrinfo IMiami->getaddrinfo
#define getnameinfo IMiami->getnameinfo
#define if_nametoindex IMiami->if_nametoindex
#define if_indextoname IMiami->if_indextoname
#define if_nameindex IMiami->if_nameindex
#define if_freenameindex IMiami->if_freenameindex
#define MiamiSupportsIPV6 IMiami->MiamiSupportsIPV6
#define MiamiResGetOptions IMiami->MiamiResGetOptions
#define MiamiResSetOptions IMiami->MiamiResSetOptions
#define sockatmark IMiami->sockatmark
#define MiamiSupportedCPUs IMiami->MiamiSupportedCPUs
#define MiamiGetFdCallback IMiami->MiamiGetFdCallback
#define MiamiSetFdCallback IMiami->MiamiSetFdCallback
#define MiamiGetCredentials IMiami->MiamiGetCredentials

#endif /* INLINE4_MIAMI_H */
