#ifndef INLINE4_MIAMI_H
#define INLINE4_MIAMI_H

/*
** This file was auto generated by idltool 50.10.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


/* Inline macros for Interface "main" */
#define MiamiSysCtl(par1, par2, par3, par4, par5, last) IMiami->MiamiSysCtl(par1, par2, par3, par4, par5, last) 
#define MiamiDisallowDNS(last) IMiami->MiamiDisallowDNS(last) 
#define MiamiGetPid() IMiami->MiamiGetPid() 
#define MiamiPFAddHook(par1, par2, last) IMiami->MiamiPFAddHook(par1, par2, last) 
#define MiamiPFRemoveHook(last) IMiami->MiamiPFRemoveHook(last) 
#define MiamiGetHardwareLen(last) IMiami->MiamiGetHardwareLen(last) 
#define MiamiOpenSSL(last) IMiami->MiamiOpenSSL(last) 
#define MiamiCloseSSL() IMiami->MiamiCloseSSL() 
#define MiamiSetSocksConn(par1, last) IMiami->MiamiSetSocksConn(par1, last) 
#define MiamiIsOnline(last) IMiami->MiamiIsOnline(last) 
#define MiamiOnOffline(par1, last) IMiami->MiamiOnOffline(par1, last) 
#define inet_ntop(par1, par2, par3, last) IMiami->inet_ntop(par1, par2, par3, last) 
#define inet_aton(par1, last) IMiami->inet_aton(par1, last) 
#define inet_pton(par1, par2, last) IMiami->inet_pton(par1, par2, last) 
#define gethostbyname2(par1, last) IMiami->gethostbyname2(par1, last) 
#define gai_strerror(last) IMiami->gai_strerror(last) 
#define freeaddrinfo(last) IMiami->freeaddrinfo(last) 
#define getaddrinfo(par1, par2, par3, last) IMiami->getaddrinfo(par1, par2, par3, last) 
#define getnameinfo(par1, par2, par3, par4, par5, par6, last) IMiami->getnameinfo(par1, par2, par3, par4, par5, par6, last) 
#define if_nametoindex(last) IMiami->if_nametoindex(last) 
#define if_indextoname(par1, last) IMiami->if_indextoname(par1, last) 
#define if_nameindex() IMiami->if_nameindex() 
#define if_freenameindex(last) IMiami->if_freenameindex(last) 
#define MiamiSupportsIPV6() IMiami->MiamiSupportsIPV6() 
#define MiamiResGetOptions() IMiami->MiamiResGetOptions() 
#define MiamiResSetOptions(last) IMiami->MiamiResSetOptions(last) 
#define sockatmark(last) IMiami->sockatmark(last) 
#define MiamiSupportedCPUs(par1, par2, last) IMiami->MiamiSupportedCPUs(par1, par2, last) 
#define MiamiGetFdCallback(last) IMiami->MiamiGetFdCallback(last) 
#define MiamiSetFdCallback(par1, last) IMiami->MiamiSetFdCallback(par1, last) 
#define MiamiGetCredentials() IMiami->MiamiGetCredentials() 

#endif /* INLINE4_MIAMI_H */
