#ifndef INLINE4_MUIMASTER_H
#define INLINE4_MUIMASTER_H

/*
** This file was auto generated by idltool 50.9.
**
** It provides compatibility to OS3 style library
** calls by substituting function names.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_MUI_H
#include <libraries/mui.h>
#endif

/* Inline substitutions for Interface "main" */
#define MUI_NewObjectA IMUIMaster->MUI_NewObjectA
#define MUI_NewObject IMUIMaster->MUI_NewObject
#define MUI_DisposeObject IMUIMaster->MUI_DisposeObject
#define MUI_RequestA IMUIMaster->MUI_RequestA
#define MUI_Request IMUIMaster->MUI_Request
#define MUI_AllocAslRequest IMUIMaster->MUI_AllocAslRequest
#define MUI_AllocAslRequestTags IMUIMaster->MUI_AllocAslRequestTags
#define MUI_AslRequest IMUIMaster->MUI_AslRequest
#define MUI_AslRequestTags IMUIMaster->MUI_AslRequestTags
#define MUI_FreeAslRequest IMUIMaster->MUI_FreeAslRequest
#define MUI_Error IMUIMaster->MUI_Error
#define MUI_SetError IMUIMaster->MUI_SetError
#define MUI_GetClass IMUIMaster->MUI_GetClass
#define MUI_FreeClass IMUIMaster->MUI_FreeClass
#define MUI_RequestIDCMP IMUIMaster->MUI_RequestIDCMP
#define MUI_RejectIDCMP IMUIMaster->MUI_RejectIDCMP
#define MUI_Redraw IMUIMaster->MUI_Redraw
#define MUI_CreateCustomClass IMUIMaster->MUI_CreateCustomClass
#define MUI_DeleteCustomClass IMUIMaster->MUI_DeleteCustomClass
#define MUI_MakeObjectA IMUIMaster->MUI_MakeObjectA
#define MUI_MakeObject IMUIMaster->MUI_MakeObject
#define MUI_Layout IMUIMaster->MUI_Layout
#define MUI_ObtainPen IMUIMaster->MUI_ObtainPen
#define MUI_ReleasePen IMUIMaster->MUI_ReleasePen
#define MUI_AddClipping IMUIMaster->MUI_AddClipping
#define MUI_RemoveClipping IMUIMaster->MUI_RemoveClipping
#define MUI_AddClipRegion IMUIMaster->MUI_AddClipRegion
#define MUI_RemoveClipRegion IMUIMaster->MUI_RemoveClipRegion
#define MUI_BeginRefresh IMUIMaster->MUI_BeginRefresh
#define MUI_EndRefresh IMUIMaster->MUI_EndRefresh

#endif /* INLINE4_MUIMASTER_H */
