#ifndef INLINE4_OPENURL_H
#define INLINE4_OPENURL_H

/*
** This file was auto generated by idltool 50.10.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_OPENURL_H
#include <libraries/openurl.h>
#endif

/* Inline macros for Interface "main" */
#define URL_OpenA(par1, last) IOpenURL->URL_OpenA(par1, last) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define URL_Open(...) IOpenURL->URL_Open(__VA_ARGS__) 
#endif
#define URL_GetPrefs() IOpenURL->URL_GetPrefs() 
#define URL_FreePrefs(last) IOpenURL->URL_FreePrefs(last) 
#define URL_SetPrefs(par1, last) IOpenURL->URL_SetPrefs(par1, last) 
#define URL_GetDefaultPrefs() IOpenURL->URL_GetDefaultPrefs() 
#define URL_LaunchPrefsApp() IOpenURL->URL_LaunchPrefsApp() 

#endif /* INLINE4_OPENURL_H */
