#ifndef INLINE4_OPENURL_H
#define INLINE4_OPENURL_H

/*
** This file was auto generated by idltool 50.9.
**
** It provides compatibility to OS3 style library
** calls by substituting function names.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_OPENURL_H
#include <libraries/openurl.h>
#endif

/* Inline substitutions for Interface "main" */
#define URL_OpenA IOpenURL->URL_OpenA
#define URL_Open IOpenURL->URL_Open
#define URL_GetPrefs IOpenURL->URL_GetPrefs
#define URL_FreePrefs IOpenURL->URL_FreePrefs
#define URL_SetPrefs IOpenURL->URL_SetPrefs
#define URL_GetDefaultPrefs IOpenURL->URL_GetDefaultPrefs
#define URL_LaunchPrefsApp IOpenURL->URL_LaunchPrefsApp

#endif /* INLINE4_OPENURL_H */
