#ifndef INLINE4_SOCKET_H
#define INLINE4_SOCKET_H

/*
** This file was auto generated by idltool 50.10.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_SOCKET_H
#include <libraries/socket.h>
#endif

/* Inline macros for Interface "main" */
#define Socket(par1, par2, last) ISocket->Socket(par1, par2, last) 
#define Connect(par1, par2, last) ISocket->Connect(par1, par2, last) 
#define Send(par1, par2, par3, last) ISocket->Send(par1, par2, par3, last) 
#define Recv(par1, par2, par3, last) ISocket->Recv(par1, par2, par3, last) 
#define Shutdown(par1, last) ISocket->Shutdown(par1, last) 
#define IoctlSocket(par1, par2, last) ISocket->IoctlSocket(par1, par2, last) 
#define CloseSocket(last) ISocket->CloseSocket(last) 
#define ObtainSocket(par1, par2, par3, last) ISocket->ObtainSocket(par1, par2, par3, last) 
#define ReleaseSocket(par1, last) ISocket->ReleaseSocket(par1, last) 
#define ReleaseCopyOfSocket(par1, last) ISocket->ReleaseCopyOfSocket(par1, last) 
#define Errno() ISocket->Errno() 
#define SetErrnoPtr(par1, last) ISocket->SetErrnoPtr(par1, last) 
#define Inet_NtoA(last) ISocket->Inet_NtoA(last) 
#define Inet_LnaOf(last) ISocket->Inet_LnaOf(last) 
#define Inet_NetOf(last) ISocket->Inet_NetOf(last) 
#define Inet_MakeAddr(par1, last) ISocket->Inet_MakeAddr(par1, last) 
#define GetHostByName(last) ISocket->GetHostByName(last) 
#define Dup2Socket(par1, last) ISocket->Dup2Socket(par1, last) 
#define SocketBaseTagList(last) ISocket->SocketBaseTagList(last) 
#if !defined(__cplusplus) && (__STDC_VERSION__ >= 199901L || __GNUC__ >= 3 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 95))
#define SocketBaseTags(...) ISocket->SocketBaseTags(__VA_ARGS__) 
#endif
#define GetSocketEvents(last) ISocket->GetSocketEvents(last) 

#endif /* INLINE4_SOCKET_H */
