#ifndef INLINE4_SOCKET_H
#define INLINE4_SOCKET_H

/*
** This file was auto generated by idltool 50.9.
**
** It provides compatibility to OS3 style library
** calls by substituting function names.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_SOCKET_H
#include <libraries/socket.h>
#endif

/* Inline substitutions for Interface "main" */
#define Socket ISocket->Socket
#define Connect ISocket->Connect
#define Send ISocket->Send
#define Recv ISocket->Recv
#define Shutdown ISocket->Shutdown
#define IoctlSocket ISocket->IoctlSocket
#define CloseSocket ISocket->CloseSocket
#define ObtainSocket ISocket->ObtainSocket
#define ReleaseSocket ISocket->ReleaseSocket
#define ReleaseCopyOfSocket ISocket->ReleaseCopyOfSocket
#define Errno ISocket->Errno
#define SetErrnoPtr ISocket->SetErrnoPtr
#define Inet_NtoA ISocket->Inet_NtoA
#define Inet_LnaOf ISocket->Inet_LnaOf
#define Inet_NetOf ISocket->Inet_NetOf
#define Inet_MakeAddr ISocket->Inet_MakeAddr
#define GetHostByName ISocket->GetHostByName
#define Dup2Socket ISocket->Dup2Socket
#define SocketBaseTagList ISocket->SocketBaseTagList
#define SocketBaseTags ISocket->SocketBaseTags
#define GetSocketEvents ISocket->GetSocketEvents

#endif /* INLINE4_SOCKET_H */
