#ifndef INLINE4_XPKMASTER_H
#define INLINE4_XPKMASTER_H

/*
** This file was auto generated by idltool 50.9.
**
** It provides compatibility to OS3 style library
** calls by substituting function names.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef XPK_XPK_H
#include <xpk/xpk.h>
#endif

/* Inline substitutions for Interface "main" */
#define XpkExamine IXpk->XpkExamine
#define XpkExamineTags IXpk->XpkExamineTags
#define XpkPack IXpk->XpkPack
#define XpkPackTags IXpk->XpkPackTags
#define XpkUnpack IXpk->XpkUnpack
#define XpkUnpackTags IXpk->XpkUnpackTags
#define XpkOpen IXpk->XpkOpen
#define XpkOpenTags IXpk->XpkOpenTags
#define XpkRead IXpk->XpkRead
#define XpkWrite IXpk->XpkWrite
#define XpkSeek IXpk->XpkSeek
#define XpkClose IXpk->XpkClose
#define XpkQuery IXpk->XpkQuery
#define XpkQueryTags IXpk->XpkQueryTags
#define XpkAllocObject IXpk->XpkAllocObject
#define XpkAllocObjectTags IXpk->XpkAllocObjectTags
#define XpkFreeObject IXpk->XpkFreeObject
#define XpkPrintFault IXpk->XpkPrintFault
#define XpkFault IXpk->XpkFault
#define XpkPassRequest IXpk->XpkPassRequest
#define XpkPassRequestTags IXpk->XpkPassRequestTags

#endif /* INLINE4_XPKMASTER_H */
