/***************************************************************************

 YAM - Yet Another Mailer
 Copyright (C) 1995-2000 by Marcel Beck <mbeck@yam.ch>
 Copyright (C) 2000-2001 by YAM Open Source Team

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 YAM Official Support Site :  http://www.yam.ch/
 YAM OpenSource project    :  http://sourceforge.net/projects/yamos/

 $Id$

***************************************************************************/

 /* This file is automatically generated with GenClasses - PLEASE DO NOT EDIT!!! */

#ifndef ADDRMATCHLIST_H
#define ADDRMATCHLIST_H

#ifndef CLASSES_CLASSES_H
#include "Classes.h"
#endif /* CLASSES_CLASSES_H */

#define DECLARE(method)  ULONG m_Addrmatchlist_## method( struct IClass *cl, Object *obj, struct MUIP_Addrmatchlist_## method *msg )
#define OVERLOAD(method) ULONG m_Addrmatchlist_## method( struct IClass *cl, Object *obj, Msg msg )
#define ATTR(attr)       case MUIA_Addrmatchlist_## attr

/* Exported CLASSDATA */

struct Data
{

	Object *Matchlist, *String;
	BOOL Open;

};

ULONG AddrmatchlistGetSize( void ) { return sizeof(struct Data); }

#endif /* ADDRMATCHLIST_H */
