/***************************************************************************

 YAM - Yet Another Mailer
 Copyright (C) 1995-2000 by Marcel Beck <mbeck@yam.ch>
 Copyright (C) 2000-2001 by YAM Open Source Team

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 YAM Official Support Site :  http://www.yam.ch/
 YAM OpenSource project    :  http://sourceforge.net/projects/yamos/

 $Id$

***************************************************************************/

 /* This file is automatically generated with GenClasses - PLEASE DO NOT EDIT!!! */

#include <string.h>
#include "Classes.h"

struct MUI_CustomClass *YAMClasses[NUMBEROFCLASSES];

/// YAMDispatcher()
DISPATCHERPROTO(YAMDispatcher)
{
  switch(msg->MethodID)
  {
    case OM_NEW                                  : return m_YAM_OM_NEW              (cl, obj, msg);
    case OM_DISPOSE                              : return m_YAM_OM_DISPOSE          (cl, obj, msg);
  }
  return DoSuperMethodA(cl, obj, msg);
}
///

/// SearchwindowDispatcher()
DISPATCHERPROTO(SearchwindowDispatcher)
{
  switch(msg->MethodID)
  {
    case OM_NEW                                  : return m_Searchwindow_OM_NEW              (cl, obj, msg);
    case MUIM_Searchwindow_Open                  : return m_Searchwindow_Open                (cl, obj, (APTR)msg);
    case MUIM_Searchwindow_Close                 : return m_Searchwindow_Close               (cl, obj, (APTR)msg);
    case MUIM_Searchwindow_Search                : return m_Searchwindow_Search              (cl, obj, (APTR)msg);
    case MUIM_Searchwindow_Next                  : return m_Searchwindow_Next                (cl, obj, (APTR)msg);
  }
  return DoSuperMethodA(cl, obj, msg);
}
///

/// RecipientstringDispatcher()
DISPATCHERPROTO(RecipientstringDispatcher)
{
  switch(msg->MethodID)
  {
    case OM_NEW                                  : return m_Recipientstring_OM_NEW              (cl, obj, msg);
    case OM_DISPOSE                              : return m_Recipientstring_OM_DISPOSE          (cl, obj, msg);
    case OM_GET                                  : return m_Recipientstring_OM_GET              (cl, obj, msg);
    case OM_SET                                  : return m_Recipientstring_OM_SET              (cl, obj, msg);
    case MUIM_Setup                              : return m_Recipientstring_MUIM_Setup          (cl, obj, msg);
    case MUIM_Show                               : return m_Recipientstring_MUIM_Show           (cl, obj, msg);
    case MUIM_GoActive                           : return m_Recipientstring_MUIM_GoActive       (cl, obj, msg);
    case MUIM_GoInactive                         : return m_Recipientstring_MUIM_GoInactive     (cl, obj, msg);
    case MUIM_DragQuery                          : return m_Recipientstring_MUIM_DragQuery      (cl, obj, msg);
    case MUIM_DragDrop                           : return m_Recipientstring_MUIM_DragDrop       (cl, obj, msg);
    case MUIM_Popstring_Open                     : return m_Recipientstring_MUIM_Popstring_Open (cl, obj, msg);
    case MUIM_HandleEvent                        : return m_Recipientstring_MUIM_HandleEvent    (cl, obj, msg);
    case MUIM_Recipientstring_Resolve            : return m_Recipientstring_Resolve             (cl, obj, (APTR)msg);
    case MUIM_Recipientstring_AddRecipient       : return m_Recipientstring_AddRecipient        (cl, obj, (APTR)msg);
    case MUIM_Recipientstring_RecipientStart     : return m_Recipientstring_RecipientStart      (cl, obj, (APTR)msg);
    case MUIM_Recipientstring_CurrentRecipient   : return m_Recipientstring_CurrentRecipient    (cl, obj, (APTR)msg);
  }
  return DoSuperMethodA(cl, obj, msg);
}
///

/// InfoBarDispatcher()
DISPATCHERPROTO(InfoBarDispatcher)
{
  switch(msg->MethodID)
  {
    case OM_NEW                                  : return m_InfoBar_OM_NEW              (cl, obj, msg);
    case MUIM_InfoBar_SetFolder                  : return m_InfoBar_SetFolder           (cl, obj, (APTR)msg);
    case MUIM_InfoBar_ShowGauge                  : return m_InfoBar_ShowGauge           (cl, obj, (APTR)msg);
    case MUIM_InfoBar_ShowInfoText               : return m_InfoBar_ShowInfoText        (cl, obj, (APTR)msg);
    case MUIM_InfoBar_HideBars                   : return m_InfoBar_HideBars            (cl, obj, (APTR)msg);
  }
  return DoSuperMethodA(cl, obj, msg);
}
///

/// AddrmatchlistDispatcher()
DISPATCHERPROTO(AddrmatchlistDispatcher)
{
  switch(msg->MethodID)
  {
    case OM_NEW                                  : return m_Addrmatchlist_OM_NEW              (cl, obj, msg);
    case OM_SET                                  : return m_Addrmatchlist_OM_SET              (cl, obj, msg);
    case MUIM_Addrmatchlist_ChangeWindow         : return m_Addrmatchlist_ChangeWindow        (cl, obj, (APTR)msg);
    case MUIM_Addrmatchlist_Event                : return m_Addrmatchlist_Event               (cl, obj, (APTR)msg);
    case MUIM_Addrmatchlist_Open                 : return m_Addrmatchlist_Open                (cl, obj, (APTR)msg);
  }
  return DoSuperMethodA(cl, obj, msg);
}
///

const struct
{
  STRPTR Name; STRPTR SuperClass; LONG SuperMCC; ULONG (*GetSize) (void); APTR Dispatcher;
} MCCInfo[NUMBEROFCLASSES] =
{
  { MUIC_YAM, MUIC_Application, -1, YAMGetSize, ENTRY(YAMDispatcher) },
  { MUIC_Searchwindow, MUIC_Window, -1, SearchwindowGetSize, ENTRY(SearchwindowDispatcher) },
  { MUIC_Recipientstring, MUIC_BetterString, -1, RecipientstringGetSize, ENTRY(RecipientstringDispatcher) },
  { MUIC_InfoBar, MUIC_Group, -1, InfoBarGetSize, ENTRY(InfoBarDispatcher) },
  { MUIC_Addrmatchlist, MUIC_Window, -1, AddrmatchlistGetSize, ENTRY(AddrmatchlistDispatcher) },
};

/// YAM_NewObject()
Object *YAM_NewObject(STRPTR class, ULONG tag, ...)
{
  long i;
  for(i = 0; i < NUMBEROFCLASSES; i++)
  {
    if(!strcmp(MCCInfo[i].Name, class))
    {
      return NewObjectA(YAMClasses[i]->mcc_Class, NULL, (struct TagItem *)&tag);
    }
  }
  return NULL;
}
///

/// YAM_SetupClasses()
long YAM_SetupClasses(void)
{
  long i;
  memset(YAMClasses, 0, sizeof(YAMClasses));
  for (i = 0; i < NUMBEROFCLASSES; i++)
  {
    struct MUI_CustomClass *superMCC = MCCInfo[i].SuperMCC == -1 ? NULL : YAMClasses[MCCInfo[i].SuperMCC];
    YAMClasses[i] = MUI_CreateCustomClass(NULL, MCCInfo[i].SuperClass, superMCC, MCCInfo[i].GetSize(), MCCInfo[i].Dispatcher);
    if (!YAMClasses[i])
    {
      YAM_CleanupClasses();
      return 0;
    }
  }
  return 1;
}
///

/// YAM_CleanupClasses()
void YAM_CleanupClasses(void)
{
  long i;
  for (i = NUMBEROFCLASSES-1; i >= 0; i--)
  {
    MUI_DeleteCustomClass(YAMClasses[i]);
    YAMClasses[i] = NULL;
  }
}
///

