#ifndef GUIGFX_INTERFACE_DEF_H
#define GUIGFX_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 51.3.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


struct GuiGFXIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct GuiGFXIFace *Self);
	ULONG APICALL (*Release)(struct GuiGFXIFace *Self);
	void APICALL (*Expunge)(struct GuiGFXIFace *Self);
	struct Interface * APICALL (*Clone)(struct GuiGFXIFace *Self);
	APTR APICALL (*MakePictureA)(struct GuiGFXIFace *Self, APTR array, UWORD width, UWORD height, struct TagItem * tags);
	APTR APICALL (*MakePicture)(struct GuiGFXIFace *Self, APTR array, UWORD width, UWORD height, ...);
	APTR APICALL (*LoadPictureA)(struct GuiGFXIFace *Self, STRPTR filename, struct TagItem * tags);
	APTR APICALL (*LoadPicture)(struct GuiGFXIFace *Self, STRPTR filename, ...);
	APTR APICALL (*ReadPictureA)(struct GuiGFXIFace *Self, struct RastPort * a0arg, struct ColorMap * colormap, UWORD x, UWORD y, UWORD width, UWORD height, struct TagItem * tags);
	APTR APICALL (*ReadPicture)(struct GuiGFXIFace *Self, struct RastPort * a0arg, struct ColorMap * colormap, UWORD x, UWORD y, UWORD width, UWORD height, ...);
	APTR APICALL (*ClonePictureA)(struct GuiGFXIFace *Self, APTR pic, struct TagItem * tags);
	APTR APICALL (*ClonePicture)(struct GuiGFXIFace *Self, APTR pic, ...);
	void APICALL (*DeletePicture)(struct GuiGFXIFace *Self, APTR pic);
	BOOL APICALL (*UpdatePicture)(struct GuiGFXIFace *Self, APTR pic);
	APTR APICALL (*AddPictureA)(struct GuiGFXIFace *Self, APTR psm, APTR pic, struct TagItem * tags);
	APTR APICALL (*AddPicture)(struct GuiGFXIFace *Self, APTR psm, APTR pic, ...);
	APTR APICALL (*AddPaletteA)(struct GuiGFXIFace *Self, APTR psm, APTR palette, struct TagItem * tags);
	APTR APICALL (*AddPalette)(struct GuiGFXIFace *Self, APTR psm, APTR palette, ...);
	APTR APICALL (*AddPixelArrayA)(struct GuiGFXIFace *Self, APTR psm, APTR array, UWORD width, UWORD height, struct TagItem * tags);
	APTR APICALL (*AddPixelArray)(struct GuiGFXIFace *Self, APTR psm, APTR array, UWORD width, UWORD height, ...);
	void APICALL (*RemColorHandle)(struct GuiGFXIFace *Self, APTR colorhandle);
	APTR APICALL (*CreatePenShareMapA)(struct GuiGFXIFace *Self, struct TagItem * tags);
	APTR APICALL (*CreatePenShareMap)(struct GuiGFXIFace *Self, ...);
	void APICALL (*DeletePenShareMap)(struct GuiGFXIFace *Self, APTR psm);
	APTR APICALL (*ObtainDrawHandleA)(struct GuiGFXIFace *Self, APTR psm, struct RastPort * a1arg, struct ColorMap * cm, struct TagItem * tags);
	APTR APICALL (*ObtainDrawHandle)(struct GuiGFXIFace *Self, APTR psm, struct RastPort * a1arg, struct ColorMap * cm, ...);
	void APICALL (*ReleaseDrawHandle)(struct GuiGFXIFace *Self, APTR drawhandle);
	BOOL APICALL (*DrawPictureA)(struct GuiGFXIFace *Self, APTR drawhandle, APTR pic, UWORD x, UWORD y, struct TagItem * tags);
	BOOL APICALL (*DrawPicture)(struct GuiGFXIFace *Self, APTR drawhandle, APTR pic, UWORD x, UWORD y, ...);
	BOOL APICALL (*MapPaletteA)(struct GuiGFXIFace *Self, APTR drawhandle, APTR palette, UBYTE * pentab, struct TagItem * tags);
	BOOL APICALL (*MapPalette)(struct GuiGFXIFace *Self, APTR drawhandle, APTR palette, UBYTE * pentab, ...);
	LONG APICALL (*MapPenA)(struct GuiGFXIFace *Self, APTR drawhandle, ULONG rgb, struct TagItem * tags);
	LONG APICALL (*MapPen)(struct GuiGFXIFace *Self, APTR drawhandle, ULONG rgb, ...);
	struct BitMap * APICALL (*CreatePictureBitMapA)(struct GuiGFXIFace *Self, APTR drawhandle, APTR pic, struct TagItem * tags);
	struct BitMap * APICALL (*CreatePictureBitMap)(struct GuiGFXIFace *Self, APTR drawhandle, APTR pic, ...);
	ULONG APICALL (*DoPictureMethodA)(struct GuiGFXIFace *Self, APTR pic, ULONG method, ULONG * arguments);
	ULONG APICALL (*DoPictureMethod)(struct GuiGFXIFace *Self, APTR pic, ULONG method, ...);
	ULONG APICALL (*GetPictureAttrsA)(struct GuiGFXIFace *Self, APTR pic, struct TagItem * tags);
	ULONG APICALL (*GetPictureAttrs)(struct GuiGFXIFace *Self, APTR pic, ...);
	ULONG APICALL (*LockPictureA)(struct GuiGFXIFace *Self, APTR pic, ULONG mode, ULONG * args);
	ULONG APICALL (*LockPicture)(struct GuiGFXIFace *Self, APTR pic, ULONG mode, ...);
	void APICALL (*UnLockPicture)(struct GuiGFXIFace *Self, APTR pic, ULONG mode);
	BOOL APICALL (*IsPictureA)(struct GuiGFXIFace *Self, char * filename, struct TagItem * tags);
	BOOL APICALL (*IsPicture)(struct GuiGFXIFace *Self, char * filename, ...);
	APTR APICALL (*CreateDirectDrawHandleA)(struct GuiGFXIFace *Self, APTR drawhandle, UWORD sw, UWORD sh, UWORD dw, UWORD dh, struct TagItem * tags);
	APTR APICALL (*CreateDirectDrawHandle)(struct GuiGFXIFace *Self, APTR drawhandle, UWORD sw, UWORD sh, UWORD dw, UWORD dh, ...);
	void APICALL (*DeleteDirectDrawHandle)(struct GuiGFXIFace *Self, APTR ddh);
	BOOL APICALL (*DirectDrawTrueColorA)(struct GuiGFXIFace *Self, APTR ddh, ULONG * array, UWORD x, UWORD y, struct TagItem * tags);
	BOOL APICALL (*DirectDrawTrueColor)(struct GuiGFXIFace *Self, APTR ddh, ULONG * array, UWORD x, UWORD y, ...);
	BOOL APICALL (*CreatePictureMaskA)(struct GuiGFXIFace *Self, APTR pic, UBYTE * mask, UWORD maskwidth, struct TagItem * tags);
	BOOL APICALL (*CreatePictureMask)(struct GuiGFXIFace *Self, APTR pic, UBYTE * mask, UWORD maskwidth, ...);
};

#endif /* GUIGFX_INTERFACE_DEF_H */
