#ifndef MIAMI_INTERFACE_DEF_H
#define MIAMI_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.10.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

struct MiamiIFace
{
  struct InterfaceData Data;

  ULONG APICALL (*Obtain)(struct MiamiIFace *Self);
  ULONG APICALL (*Release)(struct MiamiIFace *Self);
  void APICALL (*Expunge)(struct MiamiIFace *Self);
  struct Interface * APICALL (*Clone)(struct MiamiIFace *Self);
  long APICALL (*MiamiSysCtl)(struct MiamiIFace *Self, long * par1, unsigned long par2, void * par3, unsigned long * par4, void * par5, long last);
  void APICALL (*Reserved1)(struct MiamiIFace *Self);
  void APICALL (*Reserved2)(struct MiamiIFace *Self);
  void APICALL (*Reserved3)(struct MiamiIFace *Self);
  void APICALL (*Reserved4)(struct MiamiIFace *Self);
  void APICALL (*Reserved5)(struct MiamiIFace *Self);
  void APICALL (*MiamiDisallowDNS)(struct MiamiIFace *Self, long last);
  void APICALL (*Reserved6)(struct MiamiIFace *Self);
  void * APICALL (*MiamiGetPid)(struct MiamiIFace *Self);
  void APICALL (*Reserved7)(struct MiamiIFace *Self);
  void APICALL (*Reserved8)(struct MiamiIFace *Self);
  void * APICALL (*MiamiPFAddHook)(struct MiamiIFace *Self, struct Hook * par1, unsigned char * par2, struct TagItem * last);
  void APICALL (*MiamiPFRemoveHook)(struct MiamiIFace *Self, void * last);
  long APICALL (*MiamiGetHardwareLen)(struct MiamiIFace *Self, char * last);
  void APICALL (*Reserved9)(struct MiamiIFace *Self);
  void APICALL (*Reserved10)(struct MiamiIFace *Self);
  void APICALL (*Reserved11)(struct MiamiIFace *Self);
  void APICALL (*Reserved12)(struct MiamiIFace *Self);
  void APICALL (*Reserved13)(struct MiamiIFace *Self);
  void APICALL (*Reserved14)(struct MiamiIFace *Self);
  struct Library * APICALL (*MiamiOpenSSL)(struct MiamiIFace *Self, struct TagItem * last);
  void APICALL (*MiamiCloseSSL)(struct MiamiIFace *Self);
  void APICALL (*Reserved15)(struct MiamiIFace *Self);
  void APICALL (*Reserved16)(struct MiamiIFace *Self);
  void APICALL (*Reserved17)(struct MiamiIFace *Self);
  void APICALL (*Reserved18)(struct MiamiIFace *Self);
  void APICALL (*Reserved19)(struct MiamiIFace *Self);
  void APICALL (*Reserved20)(struct MiamiIFace *Self);
  long APICALL (*MiamiSetSocksConn)(struct MiamiIFace *Self, struct sockaddr * par1, long last);
  void APICALL (*Reserved21)(struct MiamiIFace *Self);
  long APICALL (*MiamiIsOnline)(struct MiamiIFace *Self, char * last);
  void APICALL (*MiamiOnOffline)(struct MiamiIFace *Self, char * par1, long last);
  void APICALL (*Reserved22)(struct MiamiIFace *Self);
  char * APICALL (*inet_ntop)(struct MiamiIFace *Self, long par1, void * par2, char * par3, long last);
  long APICALL (*inet_aton)(struct MiamiIFace *Self, char * par1, struct in_addr * last);
  long APICALL (*inet_pton)(struct MiamiIFace *Self, long par1, char * par2, void * last);
  struct hostent * APICALL (*gethostbyname2)(struct MiamiIFace *Self, char * par1, long last);
  char * APICALL (*gai_strerror)(struct MiamiIFace *Self, long last);
  void APICALL (*Reserved23)(struct MiamiIFace *Self);
  void APICALL (*Reserved24)(struct MiamiIFace *Self);
  long APICALL (*getnameinfo)(struct MiamiIFace *Self, struct sockaddr * par1, long par2, char * par3, long par4, char * par5, long par6, long last);
  long APICALL (*if_nametoindex)(struct MiamiIFace *Self, char * last);
  char * APICALL (*if_indextoname)(struct MiamiIFace *Self, long par1, char * last);
  struct if_nameindex * APICALL (*if_nameindex)(struct MiamiIFace *Self);
  void APICALL (*if_freenameindex)(struct MiamiIFace *Self, struct if_nameindex * last);
  long APICALL (*MiamiSupportsIPV6)(struct MiamiIFace *Self);
  long APICALL (*MiamiResGetOptions)(struct MiamiIFace *Self);
  void APICALL (*MiamiResSetOptions)(struct MiamiIFace *Self, long last);
  long APICALL (*sockatmark)(struct MiamiIFace *Self, long last);
  void APICALL (*MiamiSupportedCPUs)(struct MiamiIFace *Self, unsigned long * par1, unsigned long * par2, unsigned long * last);
  long APICALL (*MiamiGetFdCallback)(struct MiamiIFace *Self, void ** last);
  long APICALL (*MiamiSetFdCallback)(struct MiamiIFace *Self, void * par1, long last);
  void APICALL (*Reserved25)(struct MiamiIFace *Self);
  struct UserGroupCredentials * APICALL (*MiamiGetCredentials)(struct MiamiIFace *Self);
};

#endif /* MIAMI_INTERFACE_DEF_H */
