
#ifndef GC_H
#define GC_H 1

#ifndef LISTS_H
#include "lists.h"
#endif

#define TAG_BASE      (TAG_USER + 0x00420000)
#define BUCKET_CNT    1024

#define EDIT_WARNING "This file is automatically generated with GenClasses - PLEASE DO NOT EDIT!!!"
#define HEADER_NAME  "Classes.h"
#define SOURCE_NAME  "Classes.c"
#define OBJECT_NAME  "Classes.o"

#define KEYWD_SUPERCLASS	"Superclass:"
#define KEYWD_DESC		"Description:"
#define KEYWD_CLASSDATA		"CLASSDATA"
#define KEYWD_OVERLOAD		"OVERLOAD"
#define KEYWD_DECLARE		"DECLARE"
#define KEYWD_ATTR		"ATTR"
#define KEYWD_EXPORT		"EXPORT"


struct overloaddef
{
	char *name;
};

struct declaredef
{
	char *name;
	char *params;
};

struct attrdef
{
	char *name;
};

struct exportdef
{
	char *exporttext;
};

struct classdef
{
	char *name;               /* i.e. Searchwindow */
	char *superclass;         /* i.e. MUIC_Window */
	char *desc;
	char *classdata;
	struct list overloadlist; /* list of extracted OVERLOAD() macros */
	struct list declarelist;  /* list of extracted DECLARE() macros */
	struct list attrlist;     /* list of extracted ATTR() macros */
	struct list exportlist;   /* list of extracted EXPORT blocks */

};

#endif /* GC_H */

