name: release
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-20.04
    timeout-minutes: 480

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: setup dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq || true
        sudo apt-get -qq install libc6:i386
        sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: setup env
      run : |
        echo "GITHUB_SHA7=$(echo ${GITHUB_SHA::7})" >>$GITHUB_ENV
        echo YAMVER=$(grep '#define __YAM_VERSION' src/YAM_global.c | cut -d '"' -f2 | tr -d ".") >>$GITHUB_ENV

    - name: install adtools build env
      run: |
        DOWNLOAD_PATH=https://github.com/adtools/adtools/releases/download/20170213
        curl -L ${DOWNLOAD_PATH}/adtools-utils.tar.bz2 | sudo tar xj -C /
        curl -L ${DOWNLOAD_PATH}/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C /
        curl -L ${DOWNLOAD_PATH}/adtools-ppc-amigaos.tar.bz2 | sudo tar xj -C /
        curl -L ${DOWNLOAD_PATH}/adtools-ppc-morphos.tar.bz2 | sudo tar xj -C /
        curl -L ${DOWNLOAD_PATH}/adtools-ppc-aros.tar.bz2 | sudo tar xj -C /
        curl -L ${DOWNLOAD_PATH}/adtools-i386-aros.tar.bz2 | sudo tar xj -C /
        curl -L ${DOWNLOAD_PATH}/adtools-x86_64-aros.tar.bz2 | sudo tar xj -C /

    - name: cleanup old action artifacts
      run: .github/workflows/purge_artifacts.sh ${{ secrets.GITHUB_TOKEN }}

    #- name: remote debug tmate session
    #  uses: mxschmitt/action-tmate@v1
    #  if: matrix.platform == 'os4'

    - name: build YAM release
      timeout-minutes: 480
      run: |
        export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}
        make -j1 release

    - name: upload os4 release files as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        path: YAM*-AmigaOS4-*.lha*
        name: YAM${{ env.YAMVER }}-AmigaOS4-${{ env.GITHUB_SHA7 }}.lha
      continue-on-error: true

    - name: upload os3 release files as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        path: YAM*-AmigaOS3-*.lha*
        name: YAM${{ env.YAMVER }}-AmigaOS3-${{ env.GITHUB_SHA7 }}.lha
      continue-on-error: true

    - name: upload mos release files as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        path: YAM*-MorphOS-*.lha*
        name: YAM${{ env.YAMVER }}-MorphOS-${{ env.GITHUB_SHA7 }}.lha
      continue-on-error: true
